apiVersion: 1
datasources:
  - name: Prometheus
    uid: erppreflight-prometheus
    type: prometheus
    access: proxy
    url: http://erppreflight-prometheus:9090
    isDefault: true
    editable: false
