/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Preflight Core API
 * Enterprise multi-tenant preflight analysis and clean core auditing API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../../../production-custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type exportControllerTriggerExportResponse201 = {
  data: void
  status: 201
}

export type exportControllerTriggerExportResponseSuccess = (exportControllerTriggerExportResponse201) & {
  headers: Headers;
};
;

export type exportControllerTriggerExportResponse = (exportControllerTriggerExportResponseSuccess)

export const getExportControllerTriggerExportUrl = (projectId: string,
    analysisId: string,) => {




  return `/api/v1/projects/${projectId}/analyses/${analysisId}/export`
}

export const exportControllerTriggerExport = async (projectId: string,
    analysisId: string, options?: Parameters<typeof customInstance>[1]): Promise<exportControllerTriggerExportResponse> => {

  return customInstance<exportControllerTriggerExportResponse>(getExportControllerTriggerExportUrl(projectId,analysisId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getExportControllerTriggerExportQueryKey = (projectId: string,
    analysisId: string,) => {
    return [
    'POST', `/api/v1/projects/${projectId}/analyses/${analysisId}/export`
    ] as const;
    }


export const getExportControllerTriggerExportQueryOptions = <TData = Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError = unknown>(projectId: string,
    analysisId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExportControllerTriggerExportQueryKey(projectId,analysisId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof exportControllerTriggerExport>>> = ({ signal }) => exportControllerTriggerExport(projectId,analysisId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined && analysisId !== null && analysisId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExportControllerTriggerExportQueryResult = NonNullable<Awaited<ReturnType<typeof exportControllerTriggerExport>>>
export type ExportControllerTriggerExportQueryError = unknown


export function useExportControllerTriggerExport<TData = Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError = unknown>(
 projectId: string,
    analysisId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportControllerTriggerExport>>,
          TError,
          Awaited<ReturnType<typeof exportControllerTriggerExport>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportControllerTriggerExport<TData = Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError = unknown>(
 projectId: string,
    analysisId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportControllerTriggerExport>>,
          TError,
          Awaited<ReturnType<typeof exportControllerTriggerExport>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportControllerTriggerExport<TData = Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError = unknown>(
 projectId: string,
    analysisId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useExportControllerTriggerExport<TData = Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError = unknown>(
 projectId: string,
    analysisId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExportControllerTriggerExportQueryOptions(projectId,analysisId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type exportControllerGetReportsResponse200 = {
  data: void
  status: 200
}

export type exportControllerGetReportsResponseSuccess = (exportControllerGetReportsResponse200) & {
  headers: Headers;
};
;

export type exportControllerGetReportsResponse = (exportControllerGetReportsResponseSuccess)

export const getExportControllerGetReportsUrl = (projectId: string,
    analysisId: string,) => {




  return `/api/v1/projects/${projectId}/analyses/${analysisId}/reports`
}

export const exportControllerGetReports = async (projectId: string,
    analysisId: string, options?: Parameters<typeof customInstance>[1]): Promise<exportControllerGetReportsResponse> => {

  return customInstance<exportControllerGetReportsResponse>(getExportControllerGetReportsUrl(projectId,analysisId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getExportControllerGetReportsMutationKey = () => ['exportControllerGetReports'] as const;

export const getExportControllerGetReportsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof exportControllerGetReports>>, TError,ExportControllerGetReportsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof exportControllerGetReports>>, TError,ExportControllerGetReportsMutationVariables, TContext> => {

const mutationKey = getExportControllerGetReportsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof exportControllerGetReports>>, ExportControllerGetReportsMutationVariables> = (props) => {
          const {projectId,analysisId} = props ?? {};

          return  exportControllerGetReports(projectId,analysisId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ExportControllerGetReportsMutationResult = NonNullable<Awaited<ReturnType<typeof exportControllerGetReports>>>

    export type ExportControllerGetReportsMutationError = unknown
    export type ExportControllerGetReportsMutationVariables = {projectId: string;analysisId: string}

    export const useExportControllerGetReports = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof exportControllerGetReports>>, TError,ExportControllerGetReportsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof exportControllerGetReports>>,
        TError,
        ExportControllerGetReportsMutationVariables,
        TContext
      > => {
      return useMutation(getExportControllerGetReportsMutationOptions(options), queryClient);
    }
    export type exportControllerGetDownloadResponse200 = {
  data: void
  status: 200
}

export type exportControllerGetDownloadResponseSuccess = (exportControllerGetDownloadResponse200) & {
  headers: Headers;
};
;

export type exportControllerGetDownloadResponse = (exportControllerGetDownloadResponseSuccess)

export const getExportControllerGetDownloadUrl = (reportId: string,) => {




  return `/api/v1/reports/${reportId}/download`
}

export const exportControllerGetDownload = async (reportId: string, options?: Parameters<typeof customInstance>[1]): Promise<exportControllerGetDownloadResponse> => {

  return customInstance<exportControllerGetDownloadResponse>(getExportControllerGetDownloadUrl(reportId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getExportControllerGetDownloadMutationKey = () => ['exportControllerGetDownload'] as const;

export const getExportControllerGetDownloadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof exportControllerGetDownload>>, TError,ExportControllerGetDownloadMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof exportControllerGetDownload>>, TError,ExportControllerGetDownloadMutationVariables, TContext> => {

const mutationKey = getExportControllerGetDownloadMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof exportControllerGetDownload>>, ExportControllerGetDownloadMutationVariables> = (props) => {
          const {reportId} = props ?? {};

          return  exportControllerGetDownload(reportId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ExportControllerGetDownloadMutationResult = NonNullable<Awaited<ReturnType<typeof exportControllerGetDownload>>>

    export type ExportControllerGetDownloadMutationError = unknown
    export type ExportControllerGetDownloadMutationVariables = {reportId: string}

    export const useExportControllerGetDownload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof exportControllerGetDownload>>, TError,ExportControllerGetDownloadMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof exportControllerGetDownload>>,
        TError,
        ExportControllerGetDownloadMutationVariables,
        TContext
      > => {
      return useMutation(getExportControllerGetDownloadMutationOptions(options), queryClient);
    }
