import { Role } from '@erppreflight/schemas';

export const PERMISSIONS = {
  ANALYSIS_RUN: 'analysis:run',
  ANALYSIS_VIEW: 'analysis:view',
  ARTIFACT_UPLOAD: 'artifact:upload',
  ARTIFACT_DELETE: 'artifact:delete',
  PROJECT_CREATE: 'project:create',
  PROJECT_EDIT: 'project:edit',
  PROJECT_DELETE: 'project:delete',
  PROJECT_VIEW: 'project:view',
  REPORT_EXPORT: 'report:export',
  SETTINGS_MANAGE: 'settings:manage',
  USER_INVITE: 'user:invite',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<Role, readonly Permission[]> = {
  ORGANIZATION_OWNER: [
    PERMISSIONS.ANALYSIS_RUN,
    PERMISSIONS.ANALYSIS_VIEW,
    PERMISSIONS.ARTIFACT_UPLOAD,
    PERMISSIONS.ARTIFACT_DELETE,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_EDIT,
    PERMISSIONS.PROJECT_DELETE,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.USER_INVITE,
  ],
  SECURITY_ADMIN: [
    PERMISSIONS.ANALYSIS_RUN,
    PERMISSIONS.ANALYSIS_VIEW,
    PERMISSIONS.ARTIFACT_UPLOAD,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_EDIT,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.USER_INVITE,
  ],
  LEAD_ARCHITECT: [
    PERMISSIONS.ANALYSIS_RUN,
    PERMISSIONS.ANALYSIS_VIEW,
    PERMISSIONS.ARTIFACT_UPLOAD,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_EDIT,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
  ],
  MIGRATION_CONSULTANT: [
    PERMISSIONS.ANALYSIS_RUN,
    PERMISSIONS.ANALYSIS_VIEW,
    PERMISSIONS.ARTIFACT_UPLOAD,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
  ],
  AUDITOR: [
    PERMISSIONS.ANALYSIS_VIEW,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
  ],
  VIEWER: [
    PERMISSIONS.ANALYSIS_VIEW,
    PERMISSIONS.PROJECT_VIEW,
  ],
};

export function hasPermission(role: Role, permission: Permission): boolean {
  const allowed = ROLE_PERMISSIONS[role];
  return allowed ? allowed.includes(permission) : false;
}
