/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Preflight Core API
 * Enterprise multi-tenant preflight analysis and clean core auditing API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import { customInstance } from '../../../production-custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type healthControllerGetLivenessResponse200 = {
  data: void
  status: 200
}

export type healthControllerGetLivenessResponseSuccess = (healthControllerGetLivenessResponse200) & {
  headers: Headers;
};
;

export type healthControllerGetLivenessResponse = (healthControllerGetLivenessResponseSuccess)

export const getHealthControllerGetLivenessUrl = () => {




  return `/health/liveness`
}

export const healthControllerGetLiveness = async ( options?: Parameters<typeof customInstance>[1]): Promise<healthControllerGetLivenessResponse> => {

  return customInstance<healthControllerGetLivenessResponse>(getHealthControllerGetLivenessUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthControllerGetLivenessMutationKey = () => ['healthControllerGetLiveness'] as const;

export const getHealthControllerGetLivenessMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof healthControllerGetLiveness>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof healthControllerGetLiveness>>, TError,void, TContext> => {

const mutationKey = getHealthControllerGetLivenessMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof healthControllerGetLiveness>>, void> = () => {


          return  healthControllerGetLiveness(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type HealthControllerGetLivenessMutationResult = NonNullable<Awaited<ReturnType<typeof healthControllerGetLiveness>>>

    export type HealthControllerGetLivenessMutationError = unknown


    export const useHealthControllerGetLiveness = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof healthControllerGetLiveness>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof healthControllerGetLiveness>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getHealthControllerGetLivenessMutationOptions(options), queryClient);
    }
    export type healthControllerGetReadinessResponse200 = {
  data: void
  status: 200
}

export type healthControllerGetReadinessResponseSuccess = (healthControllerGetReadinessResponse200) & {
  headers: Headers;
};
;

export type healthControllerGetReadinessResponse = (healthControllerGetReadinessResponseSuccess)

export const getHealthControllerGetReadinessUrl = () => {




  return `/health/readiness`
}

export const healthControllerGetReadiness = async ( options?: Parameters<typeof customInstance>[1]): Promise<healthControllerGetReadinessResponse> => {

  return customInstance<healthControllerGetReadinessResponse>(getHealthControllerGetReadinessUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthControllerGetReadinessMutationKey = () => ['healthControllerGetReadiness'] as const;

export const getHealthControllerGetReadinessMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof healthControllerGetReadiness>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof healthControllerGetReadiness>>, TError,void, TContext> => {

const mutationKey = getHealthControllerGetReadinessMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof healthControllerGetReadiness>>, void> = () => {


          return  healthControllerGetReadiness(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type HealthControllerGetReadinessMutationResult = NonNullable<Awaited<ReturnType<typeof healthControllerGetReadiness>>>

    export type HealthControllerGetReadinessMutationError = unknown


    export const useHealthControllerGetReadiness = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof healthControllerGetReadiness>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof healthControllerGetReadiness>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getHealthControllerGetReadinessMutationOptions(options), queryClient);
    }
