/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Preflight Core API
 * Enterprise multi-tenant preflight analysis and clean core auditing API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../../../../explorer_m2_orval_1/production-custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type exportControllerTriggerExportResponse201 = {
  data: void
  status: 201
}

export type exportControllerTriggerExportResponseSuccess = (exportControllerTriggerExportResponse201) & {
  headers: Headers;
};
;

export type exportControllerTriggerExportResponse = (exportControllerTriggerExportResponseSuccess)

export const getExportControllerTriggerExportUrl = (projectId: string,
    analysisId: string,) => {




  return `/api/v1/projects/${projectId}/analyses/${analysisId}/export`
}

export const exportControllerTriggerExport = async (projectId: string,
    analysisId: string, options?: Parameters<typeof customInstance>[1]): Promise<exportControllerTriggerExportResponse> => {

  return customInstance<exportControllerTriggerExportResponse>(getExportControllerTriggerExportUrl(projectId,analysisId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getExportControllerTriggerExportMutationKey = () => ['exportControllerTriggerExport'] as const;

export const getExportControllerTriggerExportMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError,ExportControllerTriggerExportMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError,ExportControllerTriggerExportMutationVariables, TContext> => {

const mutationKey = getExportControllerTriggerExportMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof exportControllerTriggerExport>>, ExportControllerTriggerExportMutationVariables> = (props) => {
          const {projectId,analysisId} = props ?? {};

          return  exportControllerTriggerExport(projectId,analysisId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ExportControllerTriggerExportMutationResult = NonNullable<Awaited<ReturnType<typeof exportControllerTriggerExport>>>

    export type ExportControllerTriggerExportMutationError = unknown
    export type ExportControllerTriggerExportMutationVariables = {projectId: string;analysisId: string}

    export const useExportControllerTriggerExport = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError,ExportControllerTriggerExportMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof exportControllerTriggerExport>>,
        TError,
        ExportControllerTriggerExportMutationVariables,
        TContext
      > => {
      return useMutation(getExportControllerTriggerExportMutationOptions(options), queryClient);
    }
    export type exportControllerGetReportsResponse200 = {
  data: void
  status: 200
}

export type exportControllerGetReportsResponseSuccess = (exportControllerGetReportsResponse200) & {
  headers: Headers;
};
;

export type exportControllerGetReportsResponse = (exportControllerGetReportsResponseSuccess)

export const getExportControllerGetReportsUrl = (projectId: string,
    analysisId: string,) => {




  return `/api/v1/projects/${projectId}/analyses/${analysisId}/reports`
}

export const exportControllerGetReports = async (projectId: string,
    analysisId: string, options?: Parameters<typeof customInstance>[1]): Promise<exportControllerGetReportsResponse> => {

  return customInstance<exportControllerGetReportsResponse>(getExportControllerGetReportsUrl(projectId,analysisId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getExportControllerGetReportsQueryKey = (projectId: string,
    analysisId: string,) => {
    return [
    `/api/v1/projects/${projectId}/analyses/${analysisId}/reports`
    ] as const;
    }


export const getExportControllerGetReportsQueryOptions = <TData = Awaited<ReturnType<typeof exportControllerGetReports>>, TError = unknown>(projectId: string,
    analysisId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportControllerGetReports>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExportControllerGetReportsQueryKey(projectId,analysisId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof exportControllerGetReports>>> = ({ signal }) => exportControllerGetReports(projectId,analysisId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined && analysisId !== null && analysisId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof exportControllerGetReports>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExportControllerGetReportsQueryResult = NonNullable<Awaited<ReturnType<typeof exportControllerGetReports>>>
export type ExportControllerGetReportsQueryError = unknown


export function useExportControllerGetReports<TData = Awaited<ReturnType<typeof exportControllerGetReports>>, TError = unknown>(
 projectId: string,
    analysisId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportControllerGetReports>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportControllerGetReports>>,
          TError,
          Awaited<ReturnType<typeof exportControllerGetReports>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportControllerGetReports<TData = Awaited<ReturnType<typeof exportControllerGetReports>>, TError = unknown>(
 projectId: string,
    analysisId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportControllerGetReports>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportControllerGetReports>>,
          TError,
          Awaited<ReturnType<typeof exportControllerGetReports>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportControllerGetReports<TData = Awaited<ReturnType<typeof exportControllerGetReports>>, TError = unknown>(
 projectId: string,
    analysisId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportControllerGetReports>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useExportControllerGetReports<TData = Awaited<ReturnType<typeof exportControllerGetReports>>, TError = unknown>(
 projectId: string,
    analysisId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportControllerGetReports>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExportControllerGetReportsQueryOptions(projectId,analysisId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type exportControllerGetDownloadResponse200 = {
  data: void
  status: 200
}

export type exportControllerGetDownloadResponseSuccess = (exportControllerGetDownloadResponse200) & {
  headers: Headers;
};
;

export type exportControllerGetDownloadResponse = (exportControllerGetDownloadResponseSuccess)

export const getExportControllerGetDownloadUrl = (reportId: string,) => {




  return `/api/v1/reports/${reportId}/download`
}

export const exportControllerGetDownload = async (reportId: string, options?: Parameters<typeof customInstance>[1]): Promise<exportControllerGetDownloadResponse> => {

  return customInstance<exportControllerGetDownloadResponse>(getExportControllerGetDownloadUrl(reportId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getExportControllerGetDownloadQueryKey = (reportId: string,) => {
    return [
    `/api/v1/reports/${reportId}/download`
    ] as const;
    }


export const getExportControllerGetDownloadQueryOptions = <TData = Awaited<ReturnType<typeof exportControllerGetDownload>>, TError = unknown>(reportId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportControllerGetDownload>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExportControllerGetDownloadQueryKey(reportId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof exportControllerGetDownload>>> = ({ signal }) => exportControllerGetDownload(reportId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: reportId !== null && reportId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof exportControllerGetDownload>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExportControllerGetDownloadQueryResult = NonNullable<Awaited<ReturnType<typeof exportControllerGetDownload>>>
export type ExportControllerGetDownloadQueryError = unknown


export function useExportControllerGetDownload<TData = Awaited<ReturnType<typeof exportControllerGetDownload>>, TError = unknown>(
 reportId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportControllerGetDownload>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportControllerGetDownload>>,
          TError,
          Awaited<ReturnType<typeof exportControllerGetDownload>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportControllerGetDownload<TData = Awaited<ReturnType<typeof exportControllerGetDownload>>, TError = unknown>(
 reportId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportControllerGetDownload>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportControllerGetDownload>>,
          TError,
          Awaited<ReturnType<typeof exportControllerGetDownload>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportControllerGetDownload<TData = Awaited<ReturnType<typeof exportControllerGetDownload>>, TError = unknown>(
 reportId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportControllerGetDownload>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useExportControllerGetDownload<TData = Awaited<ReturnType<typeof exportControllerGetDownload>>, TError = unknown>(
 reportId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportControllerGetDownload>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExportControllerGetDownloadQueryOptions(reportId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






