/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Preflight Core API
 * Enterprise multi-tenant preflight analysis and clean core auditing API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';





export type healthControllerGetLivenessResponse200 = {
  data: void
  status: 200
}

export type healthControllerGetLivenessResponseSuccess = (healthControllerGetLivenessResponse200) & {
  headers: Headers;
};
;

export type healthControllerGetLivenessResponse = (healthControllerGetLivenessResponseSuccess)

export const getHealthControllerGetLivenessUrl = () => {




  return `http://localhost:4000/health/liveness`
}

export const healthControllerGetLiveness = async ( options?: RequestInit): Promise<healthControllerGetLivenessResponse> => {

  const res = await fetch(getHealthControllerGetLivenessUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthControllerGetLivenessResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as healthControllerGetLivenessResponse
}





export const getHealthControllerGetLivenessMutationKey = () => ['healthControllerGetLiveness'] as const;

export const getHealthControllerGetLivenessMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof healthControllerGetLiveness>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof healthControllerGetLiveness>>, TError,void, TContext> => {

const mutationKey = getHealthControllerGetLivenessMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof healthControllerGetLiveness>>, void> = () => {


          return  healthControllerGetLiveness(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type HealthControllerGetLivenessMutationResult = NonNullable<Awaited<ReturnType<typeof healthControllerGetLiveness>>>

    export type HealthControllerGetLivenessMutationError = unknown


    export const useHealthControllerGetLiveness = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof healthControllerGetLiveness>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof healthControllerGetLiveness>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getHealthControllerGetLivenessMutationOptions(options), queryClient);
    }
    export type healthControllerGetReadinessResponse200 = {
  data: void
  status: 200
}

export type healthControllerGetReadinessResponseSuccess = (healthControllerGetReadinessResponse200) & {
  headers: Headers;
};
;

export type healthControllerGetReadinessResponse = (healthControllerGetReadinessResponseSuccess)

export const getHealthControllerGetReadinessUrl = () => {




  return `http://localhost:4000/health/readiness`
}

export const healthControllerGetReadiness = async ( options?: RequestInit): Promise<healthControllerGetReadinessResponse> => {

  const res = await fetch(getHealthControllerGetReadinessUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthControllerGetReadinessResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as healthControllerGetReadinessResponse
}





export const getHealthControllerGetReadinessMutationKey = () => ['healthControllerGetReadiness'] as const;

export const getHealthControllerGetReadinessMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof healthControllerGetReadiness>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof healthControllerGetReadiness>>, TError,void, TContext> => {

const mutationKey = getHealthControllerGetReadinessMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof healthControllerGetReadiness>>, void> = () => {


          return  healthControllerGetReadiness(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type HealthControllerGetReadinessMutationResult = NonNullable<Awaited<ReturnType<typeof healthControllerGetReadiness>>>

    export type HealthControllerGetReadinessMutationError = unknown


    export const useHealthControllerGetReadiness = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof healthControllerGetReadiness>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof healthControllerGetReadiness>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getHealthControllerGetReadinessMutationOptions(options), queryClient);
    }
