/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Preflight Core API
 * Enterprise multi-tenant preflight analysis and clean core auditing API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  AuditControllerGetEventsParams
} from '../../models';

import { customInstance } from '../../../production-custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type auditControllerVerifyLedgerResponse200 = {
  data: void
  status: 200
}

export type auditControllerVerifyLedgerResponseSuccess = (auditControllerVerifyLedgerResponse200) & {
  headers: Headers;
};
;

export type auditControllerVerifyLedgerResponse = (auditControllerVerifyLedgerResponseSuccess)

export const getAuditControllerVerifyLedgerUrl = () => {




  return `/api/v1/audit/verify`
}

export const auditControllerVerifyLedger = async ( options?: Parameters<typeof customInstance>[1]): Promise<auditControllerVerifyLedgerResponse> => {

  return customInstance<auditControllerVerifyLedgerResponse>(getAuditControllerVerifyLedgerUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAuditControllerVerifyLedgerMutationKey = () => ['auditControllerVerifyLedger'] as const;

export const getAuditControllerVerifyLedgerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof auditControllerVerifyLedger>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof auditControllerVerifyLedger>>, TError,void, TContext> => {

const mutationKey = getAuditControllerVerifyLedgerMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof auditControllerVerifyLedger>>, void> = () => {


          return  auditControllerVerifyLedger(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuditControllerVerifyLedgerMutationResult = NonNullable<Awaited<ReturnType<typeof auditControllerVerifyLedger>>>

    export type AuditControllerVerifyLedgerMutationError = unknown


    export const useAuditControllerVerifyLedger = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof auditControllerVerifyLedger>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof auditControllerVerifyLedger>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuditControllerVerifyLedgerMutationOptions(options), queryClient);
    }
    export type auditControllerGetEventsResponse200 = {
  data: void
  status: 200
}

export type auditControllerGetEventsResponseSuccess = (auditControllerGetEventsResponse200) & {
  headers: Headers;
};
;

export type auditControllerGetEventsResponse = (auditControllerGetEventsResponseSuccess)

export const getAuditControllerGetEventsUrl = (params: AuditControllerGetEventsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/audit/events?${stringifiedParams}` : `/api/v1/audit/events`
}

export const auditControllerGetEvents = async (params: AuditControllerGetEventsParams, options?: Parameters<typeof customInstance>[1]): Promise<auditControllerGetEventsResponse> => {

  return customInstance<auditControllerGetEventsResponse>(getAuditControllerGetEventsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAuditControllerGetEventsMutationKey = () => ['auditControllerGetEvents'] as const;

export const getAuditControllerGetEventsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof auditControllerGetEvents>>, TError,AuditControllerGetEventsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof auditControllerGetEvents>>, TError,AuditControllerGetEventsMutationVariables, TContext> => {

const mutationKey = getAuditControllerGetEventsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof auditControllerGetEvents>>, AuditControllerGetEventsMutationVariables> = (props) => {
          const {params} = props ?? {};

          return  auditControllerGetEvents(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuditControllerGetEventsMutationResult = NonNullable<Awaited<ReturnType<typeof auditControllerGetEvents>>>

    export type AuditControllerGetEventsMutationError = unknown
    export type AuditControllerGetEventsMutationVariables = {params: AuditControllerGetEventsParams}

    export const useAuditControllerGetEvents = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof auditControllerGetEvents>>, TError,AuditControllerGetEventsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof auditControllerGetEvents>>,
        TError,
        AuditControllerGetEventsMutationVariables,
        TContext
      > => {
      return useMutation(getAuditControllerGetEventsMutationOptions(options), queryClient);
    }
