/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Preflight Core API
 * Enterprise multi-tenant preflight analysis and clean core auditing API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type filesControllerPresignUploadResponse201 = {
  data: void
  status: 201
}

export type filesControllerPresignUploadResponseSuccess = (filesControllerPresignUploadResponse201) & {
  headers: Headers;
};
;

export type filesControllerPresignUploadResponse = (filesControllerPresignUploadResponseSuccess)

export const getFilesControllerPresignUploadUrl = (projectId: string,) => {




  return `http://localhost:4000/api/v1/projects/${projectId}/files/presign-upload`
}

export const filesControllerPresignUpload = async (projectId: string, options?: RequestInit): Promise<filesControllerPresignUploadResponse> => {

  const res = await fetch(getFilesControllerPresignUploadUrl(projectId),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filesControllerPresignUploadResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as filesControllerPresignUploadResponse
}





export const getFilesControllerPresignUploadQueryKey = (projectId: string,) => {
    return [
    'POST', `http://localhost:4000/api/v1/projects/${projectId}/files/presign-upload`
    ] as const;
    }


export const getFilesControllerPresignUploadQueryOptions = <TData = Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError = unknown>(projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFilesControllerPresignUploadQueryKey(projectId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof filesControllerPresignUpload>>> = ({ signal }) => filesControllerPresignUpload(projectId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FilesControllerPresignUploadQueryResult = NonNullable<Awaited<ReturnType<typeof filesControllerPresignUpload>>>
export type FilesControllerPresignUploadQueryError = unknown


export function useFilesControllerPresignUpload<TData = Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError = unknown>(
 projectId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerPresignUpload>>,
          TError,
          Awaited<ReturnType<typeof filesControllerPresignUpload>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesControllerPresignUpload<TData = Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError = unknown>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerPresignUpload>>,
          TError,
          Awaited<ReturnType<typeof filesControllerPresignUpload>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesControllerPresignUpload<TData = Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError = unknown>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFilesControllerPresignUpload<TData = Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError = unknown>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFilesControllerPresignUploadQueryOptions(projectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type filesControllerConfirmUploadResponse201 = {
  data: void
  status: 201
}

export type filesControllerConfirmUploadResponseSuccess = (filesControllerConfirmUploadResponse201) & {
  headers: Headers;
};
;

export type filesControllerConfirmUploadResponse = (filesControllerConfirmUploadResponseSuccess)

export const getFilesControllerConfirmUploadUrl = (projectId: string,
    fileId: string,) => {




  return `http://localhost:4000/api/v1/projects/${projectId}/files/${fileId}/confirm`
}

export const filesControllerConfirmUpload = async (projectId: string,
    fileId: string, options?: RequestInit): Promise<filesControllerConfirmUploadResponse> => {

  const res = await fetch(getFilesControllerConfirmUploadUrl(projectId,fileId),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filesControllerConfirmUploadResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as filesControllerConfirmUploadResponse
}





export const getFilesControllerConfirmUploadQueryKey = (projectId: string,
    fileId: string,) => {
    return [
    'POST', `http://localhost:4000/api/v1/projects/${projectId}/files/${fileId}/confirm`
    ] as const;
    }


export const getFilesControllerConfirmUploadQueryOptions = <TData = Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError = unknown>(projectId: string,
    fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFilesControllerConfirmUploadQueryKey(projectId,fileId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof filesControllerConfirmUpload>>> = ({ signal }) => filesControllerConfirmUpload(projectId,fileId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined && fileId !== null && fileId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FilesControllerConfirmUploadQueryResult = NonNullable<Awaited<ReturnType<typeof filesControllerConfirmUpload>>>
export type FilesControllerConfirmUploadQueryError = unknown


export function useFilesControllerConfirmUpload<TData = Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError = unknown>(
 projectId: string,
    fileId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerConfirmUpload>>,
          TError,
          Awaited<ReturnType<typeof filesControllerConfirmUpload>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesControllerConfirmUpload<TData = Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError = unknown>(
 projectId: string,
    fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerConfirmUpload>>,
          TError,
          Awaited<ReturnType<typeof filesControllerConfirmUpload>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesControllerConfirmUpload<TData = Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError = unknown>(
 projectId: string,
    fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFilesControllerConfirmUpload<TData = Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError = unknown>(
 projectId: string,
    fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFilesControllerConfirmUploadQueryOptions(projectId,fileId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type filesControllerPresignDownloadResponse200 = {
  data: void
  status: 200
}

export type filesControllerPresignDownloadResponseSuccess = (filesControllerPresignDownloadResponse200) & {
  headers: Headers;
};
;

export type filesControllerPresignDownloadResponse = (filesControllerPresignDownloadResponseSuccess)

export const getFilesControllerPresignDownloadUrl = (projectId: string,
    fileId: string,) => {




  return `http://localhost:4000/api/v1/projects/${projectId}/files/${fileId}/presign-download`
}

export const filesControllerPresignDownload = async (projectId: string,
    fileId: string, options?: RequestInit): Promise<filesControllerPresignDownloadResponse> => {

  const res = await fetch(getFilesControllerPresignDownloadUrl(projectId,fileId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filesControllerPresignDownloadResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as filesControllerPresignDownloadResponse
}





export const getFilesControllerPresignDownloadMutationKey = () => ['filesControllerPresignDownload'] as const;

export const getFilesControllerPresignDownloadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerPresignDownload>>, TError,FilesControllerPresignDownloadMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof filesControllerPresignDownload>>, TError,FilesControllerPresignDownloadMutationVariables, TContext> => {

const mutationKey = getFilesControllerPresignDownloadMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof filesControllerPresignDownload>>, FilesControllerPresignDownloadMutationVariables> = (props) => {
          const {projectId,fileId} = props ?? {};

          return  filesControllerPresignDownload(projectId,fileId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FilesControllerPresignDownloadMutationResult = NonNullable<Awaited<ReturnType<typeof filesControllerPresignDownload>>>

    export type FilesControllerPresignDownloadMutationError = unknown
    export type FilesControllerPresignDownloadMutationVariables = {projectId: string;fileId: string}

    export const useFilesControllerPresignDownload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerPresignDownload>>, TError,FilesControllerPresignDownloadMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof filesControllerPresignDownload>>,
        TError,
        FilesControllerPresignDownloadMutationVariables,
        TContext
      > => {
      return useMutation(getFilesControllerPresignDownloadMutationOptions(options), queryClient);
    }
    export type filesControllerListFilesResponse200 = {
  data: void
  status: 200
}

export type filesControllerListFilesResponseSuccess = (filesControllerListFilesResponse200) & {
  headers: Headers;
};
;

export type filesControllerListFilesResponse = (filesControllerListFilesResponseSuccess)

export const getFilesControllerListFilesUrl = (projectId: string,) => {




  return `http://localhost:4000/api/v1/projects/${projectId}/files`
}

export const filesControllerListFiles = async (projectId: string, options?: RequestInit): Promise<filesControllerListFilesResponse> => {

  const res = await fetch(getFilesControllerListFilesUrl(projectId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filesControllerListFilesResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as filesControllerListFilesResponse
}





export const getFilesControllerListFilesMutationKey = () => ['filesControllerListFiles'] as const;

export const getFilesControllerListFilesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerListFiles>>, TError,FilesControllerListFilesMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof filesControllerListFiles>>, TError,FilesControllerListFilesMutationVariables, TContext> => {

const mutationKey = getFilesControllerListFilesMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof filesControllerListFiles>>, FilesControllerListFilesMutationVariables> = (props) => {
          const {projectId} = props ?? {};

          return  filesControllerListFiles(projectId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FilesControllerListFilesMutationResult = NonNullable<Awaited<ReturnType<typeof filesControllerListFiles>>>

    export type FilesControllerListFilesMutationError = unknown
    export type FilesControllerListFilesMutationVariables = {projectId: string}

    export const useFilesControllerListFiles = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerListFiles>>, TError,FilesControllerListFilesMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof filesControllerListFiles>>,
        TError,
        FilesControllerListFilesMutationVariables,
        TContext
      > => {
      return useMutation(getFilesControllerListFilesMutationOptions(options), queryClient);
    }
    export type filesControllerGetFileResponse200 = {
  data: void
  status: 200
}

export type filesControllerGetFileResponseSuccess = (filesControllerGetFileResponse200) & {
  headers: Headers;
};
;

export type filesControllerGetFileResponse = (filesControllerGetFileResponseSuccess)

export const getFilesControllerGetFileUrl = (projectId: string,
    fileId: string,) => {




  return `http://localhost:4000/api/v1/projects/${projectId}/files/${fileId}`
}

export const filesControllerGetFile = async (projectId: string,
    fileId: string, options?: RequestInit): Promise<filesControllerGetFileResponse> => {

  const res = await fetch(getFilesControllerGetFileUrl(projectId,fileId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filesControllerGetFileResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as filesControllerGetFileResponse
}





export const getFilesControllerGetFileMutationKey = () => ['filesControllerGetFile'] as const;

export const getFilesControllerGetFileMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerGetFile>>, TError,FilesControllerGetFileMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof filesControllerGetFile>>, TError,FilesControllerGetFileMutationVariables, TContext> => {

const mutationKey = getFilesControllerGetFileMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof filesControllerGetFile>>, FilesControllerGetFileMutationVariables> = (props) => {
          const {projectId,fileId} = props ?? {};

          return  filesControllerGetFile(projectId,fileId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FilesControllerGetFileMutationResult = NonNullable<Awaited<ReturnType<typeof filesControllerGetFile>>>

    export type FilesControllerGetFileMutationError = unknown
    export type FilesControllerGetFileMutationVariables = {projectId: string;fileId: string}

    export const useFilesControllerGetFile = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerGetFile>>, TError,FilesControllerGetFileMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof filesControllerGetFile>>,
        TError,
        FilesControllerGetFileMutationVariables,
        TContext
      > => {
      return useMutation(getFilesControllerGetFileMutationOptions(options), queryClient);
    }
