from enum import Enum


class EngineType(str, Enum):
    # Output & Extensibility
    OPD_GUARD = "OPD_GUARD"
    FORM_DOCTOR = "FORM_DOCTOR"
    CUSTOM_FIELD_FLOW_DOCTOR = "CUSTOM_FIELD_FLOW_DOCTOR"
    EXTENSION_IMPACT_GUARD = "EXTENSION_IMPACT_GUARD"

    # Migration & Clean Core
    SPRO2CLOUD = "SPRO2CLOUD"
    ECC2CLOUD_NAVIGATOR = "ECC2CLOUD_NAVIGATOR"
    SAP_GAP_RADAR = "SAP_GAP_RADAR"
    CLEAN_CORE_OBJECT_GUARD = "CLEAN_CORE_OBJECT_GUARD"

    # Integration
    CHANGE_POINTER_COVERAGE_AUDITOR = "CHANGE_POINTER_COVERAGE_AUDITOR"
    API_CHANGE_GUARD = "API_CHANGE_GUARD"

    # Release & Transport
    SOFTWARE_COLLECTION_DEPENDENCY_GUARD = "SOFTWARE_COLLECTION_DEPENDENCY_GUARD"
    TRANSPORT_DEPENDENCY_ANALYZER = "TRANSPORT_DEPENDENCY_ANALYZER"

    # Operations
    SAFE_DECOMMISSION_PREFLIGHT = "SAFE_DECOMMISSION_PREFLIGHT"
    FIORI_403_ROOT_CAUSE_DOCTOR = "FIORI_403_ROOT_CAUSE_DOCTOR"
    WORKFLOW_STUCK_EXPLAINER = "WORKFLOW_STUCK_EXPLAINER"
    IAM_COST_OPTIMIZER = "IAM_COST_OPTIMIZER"
    ACCOUNT_DETERMINATION_PREFLIGHT = "ACCOUNT_DETERMINATION_PREFLIGHT"
    SYSTEM_REFRESH_DELTA_GUARD = "SYSTEM_REFRESH_DELTA_GUARD"

    # Warehouse Automation
    MFS_BLACKBOX = "MFS_BLACKBOX"


class Severity(str, Enum):
    BLOCKER = "BLOCKER"
    CRITICAL = "CRITICAL"
    MAJOR = "MAJOR"
    MINOR = "MINOR"
    INFO = "INFO"


class ConfidenceClass(str, Enum):
    VERIFIED = "VERIFIED"          # Score: 1.0
    RULE_DERIVED = "RULE_DERIVED"  # Score: 0.85
    INFERRED = "INFERRED"          # Score: 0.60
    UNKNOWN = "UNKNOWN"            # Score: 0.30


class AnalysisStatus(str, Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    PARTIAL = "PARTIAL"


class ArtifactType(str, Enum):
    XML = "XML"
    JSON = "JSON"
    CSV = "CSV"
    ZIP = "ZIP"
    ABAP = "ABAP"
    XDP = "XDP"
    WSDL = "WSDL"
    EDMX = "EDMX"
    TXT = "TXT"
    XLSX = "XLSX"


class TrustLevel(str, Enum):
    OFFICIAL_METADATA = "OFFICIAL_METADATA"
    OFFICIAL_DOCS = "OFFICIAL_DOCS"
    CURATED_RULE = "CURATED_RULE"
    COMMUNITY = "COMMUNITY"
    CUSTOMER_EVIDENCE = "CUSTOMER_EVIDENCE"
    INFERRED = "INFERRED"
