import { escapeCsvCell, exportRawData } from '../../apps/web/src/lib/export.ts';

console.log('=== EMPIRICAL TEST: export.ts Header Handling & Data Formatting ===\n');

// Test what happens when header has comma or quotes:
const data = [
  { 'Column, With, Commas': 'Val1', 'Normal': 'Val2' }
];

// Let's inspect the CSV string generated by exportRawData logic
const headers = Object.keys(data[0]);
console.log('Raw headers array:', headers);
console.log('Joined headers in exportRawData (headers.join(",")):', headers.join(','));

if (headers.join(',').split(',').length !== 2) {
  console.log('[FAIL] Header with commas broke CSV column alignment! Headers split into', headers.join(',').split(',').length, 'columns instead of 2.');
} else {
  console.log('[PASS] Header aligned.');
}
