/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Preflight Core API
 * Enterprise multi-tenant preflight analysis and clean core auditing API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateProjectDto,
  UpdateProjectDto
} from '../../models';

import { customInstance } from '../../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type projectsControllerCreateResponse201 = {
  data: void
  status: 201
}

export type projectsControllerCreateResponseSuccess = (projectsControllerCreateResponse201) & {
  headers: Headers;
};
;

export type projectsControllerCreateResponse = (projectsControllerCreateResponseSuccess)

export const getProjectsControllerCreateUrl = () => {




  return `/api/v1/projects`
}

export const projectsControllerCreate = async (createProjectDto: CreateProjectDto, options?: Parameters<typeof customInstance>[1]): Promise<projectsControllerCreateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customInstance<projectsControllerCreateResponse>(getProjectsControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createProjectDto)
  }
);}





export const getProjectsControllerCreateQueryKey = (createProjectDto?: CreateProjectDto,) => {
    return [
    'POST', `/api/v1/projects`, createProjectDto
    ] as const;
    }


export const getProjectsControllerCreateQueryOptions = <TData = Awaited<ReturnType<typeof projectsControllerCreate>>, TError = unknown>(createProjectDto: CreateProjectDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerCreate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProjectsControllerCreateQueryKey(createProjectDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof projectsControllerCreate>>> = ({ signal }) => projectsControllerCreate(createProjectDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof projectsControllerCreate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProjectsControllerCreateQueryResult = NonNullable<Awaited<ReturnType<typeof projectsControllerCreate>>>
export type ProjectsControllerCreateQueryError = unknown


export function useProjectsControllerCreate<TData = Awaited<ReturnType<typeof projectsControllerCreate>>, TError = unknown>(
 createProjectDto: CreateProjectDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerCreate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectsControllerCreate>>,
          TError,
          Awaited<ReturnType<typeof projectsControllerCreate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProjectsControllerCreate<TData = Awaited<ReturnType<typeof projectsControllerCreate>>, TError = unknown>(
 createProjectDto: CreateProjectDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerCreate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectsControllerCreate>>,
          TError,
          Awaited<ReturnType<typeof projectsControllerCreate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProjectsControllerCreate<TData = Awaited<ReturnType<typeof projectsControllerCreate>>, TError = unknown>(
 createProjectDto: CreateProjectDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerCreate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProjectsControllerCreate<TData = Awaited<ReturnType<typeof projectsControllerCreate>>, TError = unknown>(
 createProjectDto: CreateProjectDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerCreate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProjectsControllerCreateQueryOptions(createProjectDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type projectsControllerFindAllResponse200 = {
  data: void
  status: 200
}

export type projectsControllerFindAllResponseSuccess = (projectsControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type projectsControllerFindAllResponse = (projectsControllerFindAllResponseSuccess)

export const getProjectsControllerFindAllUrl = () => {




  return `/api/v1/projects`
}

export const projectsControllerFindAll = async ( options?: Parameters<typeof customInstance>[1]): Promise<projectsControllerFindAllResponse> => {

  return customInstance<projectsControllerFindAllResponse>(getProjectsControllerFindAllUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getProjectsControllerFindAllMutationKey = () => ['projectsControllerFindAll'] as const;

export const getProjectsControllerFindAllMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerFindAll>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof projectsControllerFindAll>>, TError,void, TContext> => {

const mutationKey = getProjectsControllerFindAllMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof projectsControllerFindAll>>, void> = () => {


          return  projectsControllerFindAll(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProjectsControllerFindAllMutationResult = NonNullable<Awaited<ReturnType<typeof projectsControllerFindAll>>>

    export type ProjectsControllerFindAllMutationError = unknown


    export const useProjectsControllerFindAll = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerFindAll>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof projectsControllerFindAll>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getProjectsControllerFindAllMutationOptions(options), queryClient);
    }
    export type projectsControllerFindOneResponse200 = {
  data: void
  status: 200
}

export type projectsControllerFindOneResponseSuccess = (projectsControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type projectsControllerFindOneResponse = (projectsControllerFindOneResponseSuccess)

export const getProjectsControllerFindOneUrl = (id: string,) => {




  return `/api/v1/projects/${id}`
}

export const projectsControllerFindOne = async (id: string, options?: Parameters<typeof customInstance>[1]): Promise<projectsControllerFindOneResponse> => {

  return customInstance<projectsControllerFindOneResponse>(getProjectsControllerFindOneUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getProjectsControllerFindOneMutationKey = () => ['projectsControllerFindOne'] as const;

export const getProjectsControllerFindOneMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerFindOne>>, TError,ProjectsControllerFindOneMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof projectsControllerFindOne>>, TError,ProjectsControllerFindOneMutationVariables, TContext> => {

const mutationKey = getProjectsControllerFindOneMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof projectsControllerFindOne>>, ProjectsControllerFindOneMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  projectsControllerFindOne(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProjectsControllerFindOneMutationResult = NonNullable<Awaited<ReturnType<typeof projectsControllerFindOne>>>

    export type ProjectsControllerFindOneMutationError = unknown
    export type ProjectsControllerFindOneMutationVariables = {id: string}

    export const useProjectsControllerFindOne = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerFindOne>>, TError,ProjectsControllerFindOneMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof projectsControllerFindOne>>,
        TError,
        ProjectsControllerFindOneMutationVariables,
        TContext
      > => {
      return useMutation(getProjectsControllerFindOneMutationOptions(options), queryClient);
    }
    export type projectsControllerUpdateResponse200 = {
  data: void
  status: 200
}

export type projectsControllerUpdateResponseSuccess = (projectsControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type projectsControllerUpdateResponse = (projectsControllerUpdateResponseSuccess)

export const getProjectsControllerUpdateUrl = (id: string,) => {




  return `/api/v1/projects/${id}`
}

export const projectsControllerUpdate = async (id: string,
    updateProjectDto: UpdateProjectDto, options?: Parameters<typeof customInstance>[1]): Promise<projectsControllerUpdateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customInstance<projectsControllerUpdateResponse>(getProjectsControllerUpdateUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateProjectDto)
  }
);}





export const getProjectsControllerUpdateQueryKey = (id: string,
    updateProjectDto?: UpdateProjectDto,) => {
    return [
    'PUT', `/api/v1/projects/${id}`, updateProjectDto
    ] as const;
    }


export const getProjectsControllerUpdateQueryOptions = <TData = Awaited<ReturnType<typeof projectsControllerUpdate>>, TError = unknown>(id: string,
    updateProjectDto: UpdateProjectDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerUpdate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProjectsControllerUpdateQueryKey(id,updateProjectDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof projectsControllerUpdate>>> = ({ signal }) => projectsControllerUpdate(id,updateProjectDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof projectsControllerUpdate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProjectsControllerUpdateQueryResult = NonNullable<Awaited<ReturnType<typeof projectsControllerUpdate>>>
export type ProjectsControllerUpdateQueryError = unknown


export function useProjectsControllerUpdate<TData = Awaited<ReturnType<typeof projectsControllerUpdate>>, TError = unknown>(
 id: string,
    updateProjectDto: UpdateProjectDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerUpdate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectsControllerUpdate>>,
          TError,
          Awaited<ReturnType<typeof projectsControllerUpdate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProjectsControllerUpdate<TData = Awaited<ReturnType<typeof projectsControllerUpdate>>, TError = unknown>(
 id: string,
    updateProjectDto: UpdateProjectDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerUpdate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectsControllerUpdate>>,
          TError,
          Awaited<ReturnType<typeof projectsControllerUpdate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProjectsControllerUpdate<TData = Awaited<ReturnType<typeof projectsControllerUpdate>>, TError = unknown>(
 id: string,
    updateProjectDto: UpdateProjectDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerUpdate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProjectsControllerUpdate<TData = Awaited<ReturnType<typeof projectsControllerUpdate>>, TError = unknown>(
 id: string,
    updateProjectDto: UpdateProjectDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerUpdate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProjectsControllerUpdateQueryOptions(id,updateProjectDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type projectsControllerRemoveResponse200 = {
  data: void
  status: 200
}

export type projectsControllerRemoveResponseSuccess = (projectsControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type projectsControllerRemoveResponse = (projectsControllerRemoveResponseSuccess)

export const getProjectsControllerRemoveUrl = (id: string,) => {




  return `/api/v1/projects/${id}`
}

export const projectsControllerRemove = async (id: string, options?: Parameters<typeof customInstance>[1]): Promise<projectsControllerRemoveResponse> => {

  return customInstance<projectsControllerRemoveResponse>(getProjectsControllerRemoveUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getProjectsControllerRemoveQueryKey = (id: string,) => {
    return [
    'DELETE', `/api/v1/projects/${id}`
    ] as const;
    }


export const getProjectsControllerRemoveQueryOptions = <TData = Awaited<ReturnType<typeof projectsControllerRemove>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerRemove>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProjectsControllerRemoveQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof projectsControllerRemove>>> = ({ signal }) => projectsControllerRemove(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof projectsControllerRemove>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProjectsControllerRemoveQueryResult = NonNullable<Awaited<ReturnType<typeof projectsControllerRemove>>>
export type ProjectsControllerRemoveQueryError = unknown


export function useProjectsControllerRemove<TData = Awaited<ReturnType<typeof projectsControllerRemove>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerRemove>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectsControllerRemove>>,
          TError,
          Awaited<ReturnType<typeof projectsControllerRemove>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProjectsControllerRemove<TData = Awaited<ReturnType<typeof projectsControllerRemove>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerRemove>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectsControllerRemove>>,
          TError,
          Awaited<ReturnType<typeof projectsControllerRemove>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProjectsControllerRemove<TData = Awaited<ReturnType<typeof projectsControllerRemove>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerRemove>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProjectsControllerRemove<TData = Awaited<ReturnType<typeof projectsControllerRemove>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerRemove>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProjectsControllerRemoveQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






