/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Preflight Core API
 * Enterprise multi-tenant preflight analysis and clean core auditing API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  UpdateWorkspaceDto
} from '../../models';

import { customInstance } from '../../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type workspacesControllerGetCurrentResponse200 = {
  data: void
  status: 200
}

export type workspacesControllerGetCurrentResponseSuccess = (workspacesControllerGetCurrentResponse200) & {
  headers: Headers;
};
;

export type workspacesControllerGetCurrentResponse = (workspacesControllerGetCurrentResponseSuccess)

export const getWorkspacesControllerGetCurrentUrl = () => {




  return `/api/v1/workspaces/current`
}

export const workspacesControllerGetCurrent = async ( options?: Parameters<typeof customInstance>[1]): Promise<workspacesControllerGetCurrentResponse> => {

  return customInstance<workspacesControllerGetCurrentResponse>(getWorkspacesControllerGetCurrentUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getWorkspacesControllerGetCurrentMutationKey = () => ['workspacesControllerGetCurrent'] as const;

export const getWorkspacesControllerGetCurrentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspacesControllerGetCurrent>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof workspacesControllerGetCurrent>>, TError,void, TContext> => {

const mutationKey = getWorkspacesControllerGetCurrentMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof workspacesControllerGetCurrent>>, void> = () => {


          return  workspacesControllerGetCurrent(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WorkspacesControllerGetCurrentMutationResult = NonNullable<Awaited<ReturnType<typeof workspacesControllerGetCurrent>>>

    export type WorkspacesControllerGetCurrentMutationError = unknown


    export const useWorkspacesControllerGetCurrent = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspacesControllerGetCurrent>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof workspacesControllerGetCurrent>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getWorkspacesControllerGetCurrentMutationOptions(options), queryClient);
    }
    export type workspacesControllerUpdateCurrentResponse200 = {
  data: void
  status: 200
}

export type workspacesControllerUpdateCurrentResponseSuccess = (workspacesControllerUpdateCurrentResponse200) & {
  headers: Headers;
};
;

export type workspacesControllerUpdateCurrentResponse = (workspacesControllerUpdateCurrentResponseSuccess)

export const getWorkspacesControllerUpdateCurrentUrl = () => {




  return `/api/v1/workspaces/current`
}

export const workspacesControllerUpdateCurrent = async (updateWorkspaceDto: UpdateWorkspaceDto, options?: Parameters<typeof customInstance>[1]): Promise<workspacesControllerUpdateCurrentResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customInstance<workspacesControllerUpdateCurrentResponse>(getWorkspacesControllerUpdateCurrentUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateWorkspaceDto)
  }
);}





export const getWorkspacesControllerUpdateCurrentQueryKey = (updateWorkspaceDto?: UpdateWorkspaceDto,) => {
    return [
    'PUT', `/api/v1/workspaces/current`, updateWorkspaceDto
    ] as const;
    }


export const getWorkspacesControllerUpdateCurrentQueryOptions = <TData = Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>, TError = unknown>(updateWorkspaceDto: UpdateWorkspaceDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWorkspacesControllerUpdateCurrentQueryKey(updateWorkspaceDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>> = ({ signal }) => workspacesControllerUpdateCurrent(updateWorkspaceDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WorkspacesControllerUpdateCurrentQueryResult = NonNullable<Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>>
export type WorkspacesControllerUpdateCurrentQueryError = unknown


export function useWorkspacesControllerUpdateCurrent<TData = Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>, TError = unknown>(
 updateWorkspaceDto: UpdateWorkspaceDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>,
          TError,
          Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorkspacesControllerUpdateCurrent<TData = Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>, TError = unknown>(
 updateWorkspaceDto: UpdateWorkspaceDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>,
          TError,
          Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorkspacesControllerUpdateCurrent<TData = Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>, TError = unknown>(
 updateWorkspaceDto: UpdateWorkspaceDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useWorkspacesControllerUpdateCurrent<TData = Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>, TError = unknown>(
 updateWorkspaceDto: UpdateWorkspaceDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWorkspacesControllerUpdateCurrentQueryOptions(updateWorkspaceDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type workspacesControllerGetMembersResponse200 = {
  data: void
  status: 200
}

export type workspacesControllerGetMembersResponseSuccess = (workspacesControllerGetMembersResponse200) & {
  headers: Headers;
};
;

export type workspacesControllerGetMembersResponse = (workspacesControllerGetMembersResponseSuccess)

export const getWorkspacesControllerGetMembersUrl = () => {




  return `/api/v1/workspaces/members`
}

export const workspacesControllerGetMembers = async ( options?: Parameters<typeof customInstance>[1]): Promise<workspacesControllerGetMembersResponse> => {

  return customInstance<workspacesControllerGetMembersResponse>(getWorkspacesControllerGetMembersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getWorkspacesControllerGetMembersMutationKey = () => ['workspacesControllerGetMembers'] as const;

export const getWorkspacesControllerGetMembersMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspacesControllerGetMembers>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof workspacesControllerGetMembers>>, TError,void, TContext> => {

const mutationKey = getWorkspacesControllerGetMembersMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof workspacesControllerGetMembers>>, void> = () => {


          return  workspacesControllerGetMembers(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WorkspacesControllerGetMembersMutationResult = NonNullable<Awaited<ReturnType<typeof workspacesControllerGetMembers>>>

    export type WorkspacesControllerGetMembersMutationError = unknown


    export const useWorkspacesControllerGetMembers = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspacesControllerGetMembers>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof workspacesControllerGetMembers>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getWorkspacesControllerGetMembersMutationOptions(options), queryClient);
    }
