/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Preflight Core API
 * Enterprise multi-tenant preflight analysis and clean core auditing API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuditControllerGetEventsParams
} from '../../models';

import { customInstance } from '../../../../explorer_m2_orval_1/production-custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type auditControllerVerifyLedgerResponse200 = {
  data: void
  status: 200
}

export type auditControllerVerifyLedgerResponseSuccess = (auditControllerVerifyLedgerResponse200) & {
  headers: Headers;
};
;

export type auditControllerVerifyLedgerResponse = (auditControllerVerifyLedgerResponseSuccess)

export const getAuditControllerVerifyLedgerUrl = () => {




  return `/api/v1/audit/verify`
}

export const auditControllerVerifyLedger = async ( options?: Parameters<typeof customInstance>[1]): Promise<auditControllerVerifyLedgerResponse> => {

  return customInstance<auditControllerVerifyLedgerResponse>(getAuditControllerVerifyLedgerUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAuditControllerVerifyLedgerQueryKey = () => {
    return [
    `/api/v1/audit/verify`
    ] as const;
    }


export const getAuditControllerVerifyLedgerQueryOptions = <TData = Awaited<ReturnType<typeof auditControllerVerifyLedger>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditControllerVerifyLedger>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuditControllerVerifyLedgerQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof auditControllerVerifyLedger>>> = ({ signal }) => auditControllerVerifyLedger({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof auditControllerVerifyLedger>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuditControllerVerifyLedgerQueryResult = NonNullable<Awaited<ReturnType<typeof auditControllerVerifyLedger>>>
export type AuditControllerVerifyLedgerQueryError = unknown


export function useAuditControllerVerifyLedger<TData = Awaited<ReturnType<typeof auditControllerVerifyLedger>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditControllerVerifyLedger>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof auditControllerVerifyLedger>>,
          TError,
          Awaited<ReturnType<typeof auditControllerVerifyLedger>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuditControllerVerifyLedger<TData = Awaited<ReturnType<typeof auditControllerVerifyLedger>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditControllerVerifyLedger>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof auditControllerVerifyLedger>>,
          TError,
          Awaited<ReturnType<typeof auditControllerVerifyLedger>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuditControllerVerifyLedger<TData = Awaited<ReturnType<typeof auditControllerVerifyLedger>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditControllerVerifyLedger>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAuditControllerVerifyLedger<TData = Awaited<ReturnType<typeof auditControllerVerifyLedger>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditControllerVerifyLedger>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuditControllerVerifyLedgerQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type auditControllerGetEventsResponse200 = {
  data: void
  status: 200
}

export type auditControllerGetEventsResponseSuccess = (auditControllerGetEventsResponse200) & {
  headers: Headers;
};
;

export type auditControllerGetEventsResponse = (auditControllerGetEventsResponseSuccess)

export const getAuditControllerGetEventsUrl = (params: AuditControllerGetEventsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/audit/events?${stringifiedParams}` : `/api/v1/audit/events`
}

export const auditControllerGetEvents = async (params: AuditControllerGetEventsParams, options?: Parameters<typeof customInstance>[1]): Promise<auditControllerGetEventsResponse> => {

  return customInstance<auditControllerGetEventsResponse>(getAuditControllerGetEventsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAuditControllerGetEventsQueryKey = (params?: AuditControllerGetEventsParams,) => {
    return [
    `/api/v1/audit/events`, ...(params ? [params] : [])
    ] as const;
    }


export const getAuditControllerGetEventsQueryOptions = <TData = Awaited<ReturnType<typeof auditControllerGetEvents>>, TError = unknown>(params: AuditControllerGetEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditControllerGetEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuditControllerGetEventsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof auditControllerGetEvents>>> = ({ signal }) => auditControllerGetEvents(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof auditControllerGetEvents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuditControllerGetEventsQueryResult = NonNullable<Awaited<ReturnType<typeof auditControllerGetEvents>>>
export type AuditControllerGetEventsQueryError = unknown


export function useAuditControllerGetEvents<TData = Awaited<ReturnType<typeof auditControllerGetEvents>>, TError = unknown>(
 params: AuditControllerGetEventsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditControllerGetEvents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof auditControllerGetEvents>>,
          TError,
          Awaited<ReturnType<typeof auditControllerGetEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuditControllerGetEvents<TData = Awaited<ReturnType<typeof auditControllerGetEvents>>, TError = unknown>(
 params: AuditControllerGetEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditControllerGetEvents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof auditControllerGetEvents>>,
          TError,
          Awaited<ReturnType<typeof auditControllerGetEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuditControllerGetEvents<TData = Awaited<ReturnType<typeof auditControllerGetEvents>>, TError = unknown>(
 params: AuditControllerGetEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditControllerGetEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAuditControllerGetEvents<TData = Awaited<ReturnType<typeof auditControllerGetEvents>>, TError = unknown>(
 params: AuditControllerGetEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditControllerGetEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuditControllerGetEventsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






