"""Explicit input contracts for all 19 engines (AGENTS.md Axiom 2 #2/#3, spec 13.10 'error handling').

Every engine is run against the adversarial probes generated by ``BaseEngine.contract_probes()``
(empty, whitespace, random bytes, {}, [], malformed JSON/XML, nesting bombs one level beyond the limit,
unrelated JSON) — both through the runner and through the HTTP API. None may produce a verdict:
status FAILED, exactly one UNKNOWN input-validation finding, no exception text, never HTTP 500.
"""

from __future__ import annotations

import base64
import io
import json
import zipfile

import pytest
from starlette.testclient import TestClient

import src.engines  # noqa: F401
from src.core.base_engine import BaseEngine
from src.core.contracts import INPUT_RULE_SUFFIXES, InputContract
from src.core.registry import EngineRegistry
from src.core.runner import EngineRunner
from src.main import create_app
from src.models.enums import AnalysisStatus, ConfidenceClass, EngineType
from src.models.request import AnalysisRequest

ENGINES = list(EngineType)
PROBES = BaseEngine.contract_probes()

LEAK_MARKERS = (
    "Traceback", 'File "', ".py\"", ".py:", "object has no attribute", "NoneType", "KeyError", "TypeError",
    "AttributeError", "IndexError", "JSONDecodeError", "ValidationError(", "RecursionError", "UnicodeDecodeError",
    "pydantic_core", "/home/", "site-packages",
)


def _assert_rejected(engine_type: EngineType, payload: dict) -> None:
    prefix = EngineRegistry.get(engine_type).get_rule_prefix()
    assert payload["status"] == "FAILED", payload
    assert len(payload["findings"]) == 1, payload["findings"]
    finding = payload["findings"][0]
    assert finding["confidence"] == "UNKNOWN"
    assert finding["confidence_score"] == 0.30
    assert finding["rule_id"].startswith(prefix + "_")
    assert finding["rule_id"][len(prefix) + 1:] in INPUT_RULE_SUFFIXES
    assert finding["remediation"].strip()
    text = json.dumps(payload)
    for marker in LEAK_MARKERS:
        assert marker not in text, f"{engine_type.value}: leaked '{marker}'"


@pytest.mark.asyncio
@pytest.mark.parametrize("engine_type", ENGINES, ids=[e.value for e in ENGINES])
@pytest.mark.parametrize("probe_name,probe", PROBES, ids=[p[0] for p in PROBES])
async def test_garbage_input_never_yields_a_verdict(engine_type, probe_name, probe):
    req = AnalysisRequest(
        job_id=f"contract-{probe_name}", tenant_id="t", project_id="p", engine_type=engine_type, **probe
    )
    resp = await EngineRunner.execute(req)
    _assert_rejected(engine_type, json.loads(resp.model_dump_json()))


@pytest.fixture(scope="module")
def api_client():
    with TestClient(create_app(), raise_server_exceptions=False) as client:
        yield client


@pytest.mark.parametrize("engine_type", ENGINES, ids=[e.value for e in ENGINES])
def test_garbage_input_over_http_is_never_500(api_client, engine_type):
    for probe_name, probe in PROBES:
        body = {"job_id": f"http-{probe_name}", "tenant_id": "t", "project_id": "p",
                "engine_type": engine_type.value, **probe}
        r = api_client.post("/api/v1/analyze", json=body)
        assert r.status_code == 200, (probe_name, r.status_code, r.text[:300])
        _assert_rejected(engine_type, r.json())


def _nested_zip(levels: int, leaf_name: str = "manifest.json", leaf: bytes = b"{}") -> bytes:
    data = leaf
    name = leaf_name
    for i in range(levels):
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
            zf.writestr(name, data)
        data = buf.getvalue()
        name = f"level{i}.zip"
    return data


ARCHIVE_ENGINES = [e for e in ENGINES if EngineRegistry.get(e).accepts_binary_input]


@pytest.mark.asyncio
@pytest.mark.parametrize("engine_type", ARCHIVE_ENGINES, ids=[e.value for e in ARCHIVE_ENGINES])
async def test_archive_nesting_one_level_too_deep_is_rejected(engine_type):
    # outer + 3 nested levels = one level beyond MAX_NESTED_ARCHIVE_LEVELS (2)
    payload = base64.b64encode(_nested_zip(4)).decode()
    req = AnalysisRequest(job_id="zip", tenant_id="t", project_id="p", engine_type=engine_type,
                          raw_content=payload, raw_content_encoding="base64")
    resp = await EngineRunner.execute(req)
    prefix = EngineRegistry.get(engine_type).get_rule_prefix()
    assert resp.status == AnalysisStatus.FAILED
    assert [f.rule_id for f in resp.findings] == [f"{prefix}_ARCHIVE_REJECTED"]
    assert "nesting" in resp.findings[0].description


@pytest.mark.parametrize("engine_type", ENGINES, ids=[e.value for e in ENGINES])
def test_every_engine_declares_an_explicit_contract(engine_type):
    engine = EngineRegistry.get(engine_type)
    contract = engine.input_contract
    assert isinstance(contract, InputContract)
    assert contract.formats and contract.summary.strip() and contract.required
    assert contract.json_model is not None, "structured (JSON / configuration) input must be schema-validated"
    described = contract.describe()
    assert described["acceptedFormats"]


@pytest.mark.asyncio
@pytest.mark.parametrize("engine_type", ENGINES, ids=[e.value for e in ENGINES])
async def test_configuration_without_data_is_insufficient(engine_type):
    req = AnalysisRequest(job_id="cfg", tenant_id="t", project_id="p", engine_type=engine_type,
                          configuration={"target_release": "S4H_2023", "unrelated": {"x": 1}})
    resp = await EngineRunner.execute(req)
    assert resp.status == AnalysisStatus.FAILED
    assert len(resp.findings) == 1 and resp.findings[0].confidence == ConfidenceClass.UNKNOWN
    assert resp.findings[0].rule_id.endswith(("_INSUFFICIENT_INPUT", "_INVALID_INPUT"))
