/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Preflight Core API
 * Enterprise multi-tenant preflight analysis and clean core auditing API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuditControllerGetEventsParams,
  CreateProjectDto,
  LoginDto,
  RegisterDto,
  UpdateProjectDto,
  UpdateWorkspaceDto
} from './models';

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type authControllerRegisterResponse201 = {
  data: void
  status: 201
}

export type authControllerRegisterResponseSuccess = (authControllerRegisterResponse201) & {
  headers: Headers;
};
;

export type authControllerRegisterResponse = (authControllerRegisterResponseSuccess)

export const getAuthControllerRegisterUrl = () => {




  return `http://localhost:4000/api/v1/auth/register`
}

export const authControllerRegister = async (registerDto: RegisterDto, options?: RequestInit): Promise<authControllerRegisterResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getAuthControllerRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(registerDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authControllerRegisterResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as authControllerRegisterResponse
}





export const getAuthControllerRegisterQueryKey = (registerDto?: RegisterDto,) => {
    return [
    'POST', `http://localhost:4000/api/v1/auth/register`, registerDto
    ] as const;
    }


export const getAuthControllerRegisterQueryOptions = <TData = Awaited<ReturnType<typeof authControllerRegister>>, TError = unknown>(registerDto: RegisterDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerRegisterQueryKey(registerDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerRegister>>> = ({ signal }) => authControllerRegister(registerDto, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerRegisterQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerRegister>>>
export type AuthControllerRegisterQueryError = unknown


export function useAuthControllerRegister<TData = Awaited<ReturnType<typeof authControllerRegister>>, TError = unknown>(
 registerDto: RegisterDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerRegister>>,
          TError,
          Awaited<ReturnType<typeof authControllerRegister>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerRegister<TData = Awaited<ReturnType<typeof authControllerRegister>>, TError = unknown>(
 registerDto: RegisterDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerRegister>>,
          TError,
          Awaited<ReturnType<typeof authControllerRegister>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerRegister<TData = Awaited<ReturnType<typeof authControllerRegister>>, TError = unknown>(
 registerDto: RegisterDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAuthControllerRegister<TData = Awaited<ReturnType<typeof authControllerRegister>>, TError = unknown>(
 registerDto: RegisterDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerRegisterQueryOptions(registerDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type authControllerLoginResponse200 = {
  data: void
  status: 200
}

export type authControllerLoginResponseSuccess = (authControllerLoginResponse200) & {
  headers: Headers;
};
;

export type authControllerLoginResponse = (authControllerLoginResponseSuccess)

export const getAuthControllerLoginUrl = () => {




  return `http://localhost:4000/api/v1/auth/login`
}

export const authControllerLogin = async (loginDto: LoginDto, options?: RequestInit): Promise<authControllerLoginResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getAuthControllerLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(loginDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authControllerLoginResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as authControllerLoginResponse
}





export const getAuthControllerLoginQueryKey = (loginDto?: LoginDto,) => {
    return [
    'POST', `http://localhost:4000/api/v1/auth/login`, loginDto
    ] as const;
    }


export const getAuthControllerLoginQueryOptions = <TData = Awaited<ReturnType<typeof authControllerLogin>>, TError = unknown>(loginDto: LoginDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerLoginQueryKey(loginDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerLogin>>> = ({ signal }) => authControllerLogin(loginDto, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerLoginQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerLogin>>>
export type AuthControllerLoginQueryError = unknown


export function useAuthControllerLogin<TData = Awaited<ReturnType<typeof authControllerLogin>>, TError = unknown>(
 loginDto: LoginDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerLogin>>,
          TError,
          Awaited<ReturnType<typeof authControllerLogin>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerLogin<TData = Awaited<ReturnType<typeof authControllerLogin>>, TError = unknown>(
 loginDto: LoginDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerLogin>>,
          TError,
          Awaited<ReturnType<typeof authControllerLogin>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerLogin<TData = Awaited<ReturnType<typeof authControllerLogin>>, TError = unknown>(
 loginDto: LoginDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAuthControllerLogin<TData = Awaited<ReturnType<typeof authControllerLogin>>, TError = unknown>(
 loginDto: LoginDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerLoginQueryOptions(loginDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type authControllerMeResponse200 = {
  data: void
  status: 200
}

export type authControllerMeResponseSuccess = (authControllerMeResponse200) & {
  headers: Headers;
};
;

export type authControllerMeResponse = (authControllerMeResponseSuccess)

export const getAuthControllerMeUrl = () => {




  return `http://localhost:4000/api/v1/auth/me`
}

export const authControllerMe = async ( options?: RequestInit): Promise<authControllerMeResponse> => {

  const res = await fetch(getAuthControllerMeUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authControllerMeResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as authControllerMeResponse
}





export const getAuthControllerMeMutationKey = () => ['authControllerMe'] as const;

export const getAuthControllerMeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerMe>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerMe>>, TError,void, TContext> => {

const mutationKey = getAuthControllerMeMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerMe>>, void> = () => {


          return  authControllerMe(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerMeMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerMe>>>

    export type AuthControllerMeMutationError = unknown


    export const useAuthControllerMe = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerMe>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerMe>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerMeMutationOptions(options), queryClient);
    }

export type workspacesControllerGetCurrentResponse200 = {
  data: void
  status: 200
}

export type workspacesControllerGetCurrentResponseSuccess = (workspacesControllerGetCurrentResponse200) & {
  headers: Headers;
};
;

export type workspacesControllerGetCurrentResponse = (workspacesControllerGetCurrentResponseSuccess)

export const getWorkspacesControllerGetCurrentUrl = () => {




  return `http://localhost:4000/api/v1/workspaces/current`
}

export const workspacesControllerGetCurrent = async ( options?: RequestInit): Promise<workspacesControllerGetCurrentResponse> => {

  const res = await fetch(getWorkspacesControllerGetCurrentUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: workspacesControllerGetCurrentResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as workspacesControllerGetCurrentResponse
}





export const getWorkspacesControllerGetCurrentMutationKey = () => ['workspacesControllerGetCurrent'] as const;

export const getWorkspacesControllerGetCurrentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspacesControllerGetCurrent>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof workspacesControllerGetCurrent>>, TError,void, TContext> => {

const mutationKey = getWorkspacesControllerGetCurrentMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof workspacesControllerGetCurrent>>, void> = () => {


          return  workspacesControllerGetCurrent(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WorkspacesControllerGetCurrentMutationResult = NonNullable<Awaited<ReturnType<typeof workspacesControllerGetCurrent>>>

    export type WorkspacesControllerGetCurrentMutationError = unknown


    export const useWorkspacesControllerGetCurrent = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspacesControllerGetCurrent>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof workspacesControllerGetCurrent>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getWorkspacesControllerGetCurrentMutationOptions(options), queryClient);
    }

export type workspacesControllerUpdateCurrentResponse200 = {
  data: void
  status: 200
}

export type workspacesControllerUpdateCurrentResponseSuccess = (workspacesControllerUpdateCurrentResponse200) & {
  headers: Headers;
};
;

export type workspacesControllerUpdateCurrentResponse = (workspacesControllerUpdateCurrentResponseSuccess)

export const getWorkspacesControllerUpdateCurrentUrl = () => {




  return `http://localhost:4000/api/v1/workspaces/current`
}

export const workspacesControllerUpdateCurrent = async (updateWorkspaceDto: UpdateWorkspaceDto, options?: RequestInit): Promise<workspacesControllerUpdateCurrentResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getWorkspacesControllerUpdateCurrentUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateWorkspaceDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: workspacesControllerUpdateCurrentResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as workspacesControllerUpdateCurrentResponse
}





export const getWorkspacesControllerUpdateCurrentQueryKey = (updateWorkspaceDto?: UpdateWorkspaceDto,) => {
    return [
    'PUT', `http://localhost:4000/api/v1/workspaces/current`, updateWorkspaceDto
    ] as const;
    }


export const getWorkspacesControllerUpdateCurrentQueryOptions = <TData = Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>, TError = unknown>(updateWorkspaceDto: UpdateWorkspaceDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWorkspacesControllerUpdateCurrentQueryKey(updateWorkspaceDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>> = ({ signal }) => workspacesControllerUpdateCurrent(updateWorkspaceDto, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WorkspacesControllerUpdateCurrentQueryResult = NonNullable<Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>>
export type WorkspacesControllerUpdateCurrentQueryError = unknown


export function useWorkspacesControllerUpdateCurrent<TData = Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>, TError = unknown>(
 updateWorkspaceDto: UpdateWorkspaceDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>,
          TError,
          Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorkspacesControllerUpdateCurrent<TData = Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>, TError = unknown>(
 updateWorkspaceDto: UpdateWorkspaceDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>,
          TError,
          Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorkspacesControllerUpdateCurrent<TData = Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>, TError = unknown>(
 updateWorkspaceDto: UpdateWorkspaceDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useWorkspacesControllerUpdateCurrent<TData = Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>, TError = unknown>(
 updateWorkspaceDto: UpdateWorkspaceDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspacesControllerUpdateCurrent>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWorkspacesControllerUpdateCurrentQueryOptions(updateWorkspaceDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type workspacesControllerGetMembersResponse200 = {
  data: void
  status: 200
}

export type workspacesControllerGetMembersResponseSuccess = (workspacesControllerGetMembersResponse200) & {
  headers: Headers;
};
;

export type workspacesControllerGetMembersResponse = (workspacesControllerGetMembersResponseSuccess)

export const getWorkspacesControllerGetMembersUrl = () => {




  return `http://localhost:4000/api/v1/workspaces/members`
}

export const workspacesControllerGetMembers = async ( options?: RequestInit): Promise<workspacesControllerGetMembersResponse> => {

  const res = await fetch(getWorkspacesControllerGetMembersUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: workspacesControllerGetMembersResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as workspacesControllerGetMembersResponse
}





export const getWorkspacesControllerGetMembersMutationKey = () => ['workspacesControllerGetMembers'] as const;

export const getWorkspacesControllerGetMembersMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspacesControllerGetMembers>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof workspacesControllerGetMembers>>, TError,void, TContext> => {

const mutationKey = getWorkspacesControllerGetMembersMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof workspacesControllerGetMembers>>, void> = () => {


          return  workspacesControllerGetMembers(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WorkspacesControllerGetMembersMutationResult = NonNullable<Awaited<ReturnType<typeof workspacesControllerGetMembers>>>

    export type WorkspacesControllerGetMembersMutationError = unknown


    export const useWorkspacesControllerGetMembers = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspacesControllerGetMembers>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof workspacesControllerGetMembers>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getWorkspacesControllerGetMembersMutationOptions(options), queryClient);
    }

export type projectsControllerCreateResponse201 = {
  data: void
  status: 201
}

export type projectsControllerCreateResponseSuccess = (projectsControllerCreateResponse201) & {
  headers: Headers;
};
;

export type projectsControllerCreateResponse = (projectsControllerCreateResponseSuccess)

export const getProjectsControllerCreateUrl = () => {




  return `http://localhost:4000/api/v1/projects`
}

export const projectsControllerCreate = async (createProjectDto: CreateProjectDto, options?: RequestInit): Promise<projectsControllerCreateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getProjectsControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createProjectDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: projectsControllerCreateResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as projectsControllerCreateResponse
}





export const getProjectsControllerCreateQueryKey = (createProjectDto?: CreateProjectDto,) => {
    return [
    'POST', `http://localhost:4000/api/v1/projects`, createProjectDto
    ] as const;
    }


export const getProjectsControllerCreateQueryOptions = <TData = Awaited<ReturnType<typeof projectsControllerCreate>>, TError = unknown>(createProjectDto: CreateProjectDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerCreate>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProjectsControllerCreateQueryKey(createProjectDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof projectsControllerCreate>>> = ({ signal }) => projectsControllerCreate(createProjectDto, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof projectsControllerCreate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProjectsControllerCreateQueryResult = NonNullable<Awaited<ReturnType<typeof projectsControllerCreate>>>
export type ProjectsControllerCreateQueryError = unknown


export function useProjectsControllerCreate<TData = Awaited<ReturnType<typeof projectsControllerCreate>>, TError = unknown>(
 createProjectDto: CreateProjectDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerCreate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectsControllerCreate>>,
          TError,
          Awaited<ReturnType<typeof projectsControllerCreate>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProjectsControllerCreate<TData = Awaited<ReturnType<typeof projectsControllerCreate>>, TError = unknown>(
 createProjectDto: CreateProjectDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerCreate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectsControllerCreate>>,
          TError,
          Awaited<ReturnType<typeof projectsControllerCreate>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProjectsControllerCreate<TData = Awaited<ReturnType<typeof projectsControllerCreate>>, TError = unknown>(
 createProjectDto: CreateProjectDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerCreate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProjectsControllerCreate<TData = Awaited<ReturnType<typeof projectsControllerCreate>>, TError = unknown>(
 createProjectDto: CreateProjectDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerCreate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProjectsControllerCreateQueryOptions(createProjectDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type projectsControllerFindAllResponse200 = {
  data: void
  status: 200
}

export type projectsControllerFindAllResponseSuccess = (projectsControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type projectsControllerFindAllResponse = (projectsControllerFindAllResponseSuccess)

export const getProjectsControllerFindAllUrl = () => {




  return `http://localhost:4000/api/v1/projects`
}

export const projectsControllerFindAll = async ( options?: RequestInit): Promise<projectsControllerFindAllResponse> => {

  const res = await fetch(getProjectsControllerFindAllUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: projectsControllerFindAllResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as projectsControllerFindAllResponse
}





export const getProjectsControllerFindAllMutationKey = () => ['projectsControllerFindAll'] as const;

export const getProjectsControllerFindAllMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerFindAll>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof projectsControllerFindAll>>, TError,void, TContext> => {

const mutationKey = getProjectsControllerFindAllMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof projectsControllerFindAll>>, void> = () => {


          return  projectsControllerFindAll(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProjectsControllerFindAllMutationResult = NonNullable<Awaited<ReturnType<typeof projectsControllerFindAll>>>

    export type ProjectsControllerFindAllMutationError = unknown


    export const useProjectsControllerFindAll = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerFindAll>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof projectsControllerFindAll>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getProjectsControllerFindAllMutationOptions(options), queryClient);
    }

export type projectsControllerFindOneResponse200 = {
  data: void
  status: 200
}

export type projectsControllerFindOneResponseSuccess = (projectsControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type projectsControllerFindOneResponse = (projectsControllerFindOneResponseSuccess)

export const getProjectsControllerFindOneUrl = (id: string,) => {




  return `http://localhost:4000/api/v1/projects/${id}`
}

export const projectsControllerFindOne = async (id: string, options?: RequestInit): Promise<projectsControllerFindOneResponse> => {

  const res = await fetch(getProjectsControllerFindOneUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: projectsControllerFindOneResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as projectsControllerFindOneResponse
}





export const getProjectsControllerFindOneMutationKey = () => ['projectsControllerFindOne'] as const;

export const getProjectsControllerFindOneMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerFindOne>>, TError,ProjectsControllerFindOneMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof projectsControllerFindOne>>, TError,ProjectsControllerFindOneMutationVariables, TContext> => {

const mutationKey = getProjectsControllerFindOneMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof projectsControllerFindOne>>, ProjectsControllerFindOneMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  projectsControllerFindOne(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProjectsControllerFindOneMutationResult = NonNullable<Awaited<ReturnType<typeof projectsControllerFindOne>>>

    export type ProjectsControllerFindOneMutationError = unknown
    export type ProjectsControllerFindOneMutationVariables = {id: string}

    export const useProjectsControllerFindOne = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerFindOne>>, TError,ProjectsControllerFindOneMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof projectsControllerFindOne>>,
        TError,
        ProjectsControllerFindOneMutationVariables,
        TContext
      > => {
      return useMutation(getProjectsControllerFindOneMutationOptions(options), queryClient);
    }

export type projectsControllerUpdateResponse200 = {
  data: void
  status: 200
}

export type projectsControllerUpdateResponseSuccess = (projectsControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type projectsControllerUpdateResponse = (projectsControllerUpdateResponseSuccess)

export const getProjectsControllerUpdateUrl = (id: string,) => {




  return `http://localhost:4000/api/v1/projects/${id}`
}

export const projectsControllerUpdate = async (id: string,
    updateProjectDto: UpdateProjectDto, options?: RequestInit): Promise<projectsControllerUpdateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getProjectsControllerUpdateUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateProjectDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: projectsControllerUpdateResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as projectsControllerUpdateResponse
}





export const getProjectsControllerUpdateQueryKey = (id: string,
    updateProjectDto?: UpdateProjectDto,) => {
    return [
    'PUT', `http://localhost:4000/api/v1/projects/${id}`, updateProjectDto
    ] as const;
    }


export const getProjectsControllerUpdateQueryOptions = <TData = Awaited<ReturnType<typeof projectsControllerUpdate>>, TError = unknown>(id: string,
    updateProjectDto: UpdateProjectDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerUpdate>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProjectsControllerUpdateQueryKey(id,updateProjectDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof projectsControllerUpdate>>> = ({ signal }) => projectsControllerUpdate(id,updateProjectDto, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof projectsControllerUpdate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProjectsControllerUpdateQueryResult = NonNullable<Awaited<ReturnType<typeof projectsControllerUpdate>>>
export type ProjectsControllerUpdateQueryError = unknown


export function useProjectsControllerUpdate<TData = Awaited<ReturnType<typeof projectsControllerUpdate>>, TError = unknown>(
 id: string,
    updateProjectDto: UpdateProjectDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerUpdate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectsControllerUpdate>>,
          TError,
          Awaited<ReturnType<typeof projectsControllerUpdate>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProjectsControllerUpdate<TData = Awaited<ReturnType<typeof projectsControllerUpdate>>, TError = unknown>(
 id: string,
    updateProjectDto: UpdateProjectDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerUpdate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectsControllerUpdate>>,
          TError,
          Awaited<ReturnType<typeof projectsControllerUpdate>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProjectsControllerUpdate<TData = Awaited<ReturnType<typeof projectsControllerUpdate>>, TError = unknown>(
 id: string,
    updateProjectDto: UpdateProjectDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerUpdate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProjectsControllerUpdate<TData = Awaited<ReturnType<typeof projectsControllerUpdate>>, TError = unknown>(
 id: string,
    updateProjectDto: UpdateProjectDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerUpdate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProjectsControllerUpdateQueryOptions(id,updateProjectDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type projectsControllerRemoveResponse200 = {
  data: void
  status: 200
}

export type projectsControllerRemoveResponseSuccess = (projectsControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type projectsControllerRemoveResponse = (projectsControllerRemoveResponseSuccess)

export const getProjectsControllerRemoveUrl = (id: string,) => {




  return `http://localhost:4000/api/v1/projects/${id}`
}

export const projectsControllerRemove = async (id: string, options?: RequestInit): Promise<projectsControllerRemoveResponse> => {

  const res = await fetch(getProjectsControllerRemoveUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: projectsControllerRemoveResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as projectsControllerRemoveResponse
}





export const getProjectsControllerRemoveQueryKey = (id: string,) => {
    return [
    'DELETE', `http://localhost:4000/api/v1/projects/${id}`
    ] as const;
    }


export const getProjectsControllerRemoveQueryOptions = <TData = Awaited<ReturnType<typeof projectsControllerRemove>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerRemove>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProjectsControllerRemoveQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof projectsControllerRemove>>> = ({ signal }) => projectsControllerRemove(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof projectsControllerRemove>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProjectsControllerRemoveQueryResult = NonNullable<Awaited<ReturnType<typeof projectsControllerRemove>>>
export type ProjectsControllerRemoveQueryError = unknown


export function useProjectsControllerRemove<TData = Awaited<ReturnType<typeof projectsControllerRemove>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerRemove>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectsControllerRemove>>,
          TError,
          Awaited<ReturnType<typeof projectsControllerRemove>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProjectsControllerRemove<TData = Awaited<ReturnType<typeof projectsControllerRemove>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerRemove>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectsControllerRemove>>,
          TError,
          Awaited<ReturnType<typeof projectsControllerRemove>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProjectsControllerRemove<TData = Awaited<ReturnType<typeof projectsControllerRemove>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerRemove>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProjectsControllerRemove<TData = Awaited<ReturnType<typeof projectsControllerRemove>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerRemove>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProjectsControllerRemoveQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type jobsControllerTriggerAnalysisResponse201 = {
  data: void
  status: 201
}

export type jobsControllerTriggerAnalysisResponseSuccess = (jobsControllerTriggerAnalysisResponse201) & {
  headers: Headers;
};
;

export type jobsControllerTriggerAnalysisResponse = (jobsControllerTriggerAnalysisResponseSuccess)

export const getJobsControllerTriggerAnalysisUrl = () => {




  return `http://localhost:4000/api/v1/jobs/analyze`
}

export const jobsControllerTriggerAnalysis = async ( options?: RequestInit): Promise<jobsControllerTriggerAnalysisResponse> => {

  const res = await fetch(getJobsControllerTriggerAnalysisUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: jobsControllerTriggerAnalysisResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as jobsControllerTriggerAnalysisResponse
}





export const getJobsControllerTriggerAnalysisQueryKey = () => {
    return [
    'POST', `http://localhost:4000/api/v1/jobs/analyze`
    ] as const;
    }


export const getJobsControllerTriggerAnalysisQueryOptions = <TData = Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getJobsControllerTriggerAnalysisQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>> = ({ signal }) => jobsControllerTriggerAnalysis({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type JobsControllerTriggerAnalysisQueryResult = NonNullable<Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>>
export type JobsControllerTriggerAnalysisQueryError = unknown


export function useJobsControllerTriggerAnalysis<TData = Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>,
          TError,
          Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useJobsControllerTriggerAnalysis<TData = Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>,
          TError,
          Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useJobsControllerTriggerAnalysis<TData = Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useJobsControllerTriggerAnalysis<TData = Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getJobsControllerTriggerAnalysisQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type jobsControllerGetAnalysisResponse200 = {
  data: void
  status: 200
}

export type jobsControllerGetAnalysisResponseSuccess = (jobsControllerGetAnalysisResponse200) & {
  headers: Headers;
};
;

export type jobsControllerGetAnalysisResponse = (jobsControllerGetAnalysisResponseSuccess)

export const getJobsControllerGetAnalysisUrl = (id: string,) => {




  return `http://localhost:4000/api/v1/jobs/${id}`
}

export const jobsControllerGetAnalysis = async (id: string, options?: RequestInit): Promise<jobsControllerGetAnalysisResponse> => {

  const res = await fetch(getJobsControllerGetAnalysisUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: jobsControllerGetAnalysisResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as jobsControllerGetAnalysisResponse
}





export const getJobsControllerGetAnalysisMutationKey = () => ['jobsControllerGetAnalysis'] as const;

export const getJobsControllerGetAnalysisMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof jobsControllerGetAnalysis>>, TError,JobsControllerGetAnalysisMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof jobsControllerGetAnalysis>>, TError,JobsControllerGetAnalysisMutationVariables, TContext> => {

const mutationKey = getJobsControllerGetAnalysisMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof jobsControllerGetAnalysis>>, JobsControllerGetAnalysisMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  jobsControllerGetAnalysis(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type JobsControllerGetAnalysisMutationResult = NonNullable<Awaited<ReturnType<typeof jobsControllerGetAnalysis>>>

    export type JobsControllerGetAnalysisMutationError = unknown
    export type JobsControllerGetAnalysisMutationVariables = {id: string}

    export const useJobsControllerGetAnalysis = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof jobsControllerGetAnalysis>>, TError,JobsControllerGetAnalysisMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof jobsControllerGetAnalysis>>,
        TError,
        JobsControllerGetAnalysisMutationVariables,
        TContext
      > => {
      return useMutation(getJobsControllerGetAnalysisMutationOptions(options), queryClient);
    }

export type healthControllerGetLivenessResponse200 = {
  data: void
  status: 200
}

export type healthControllerGetLivenessResponseSuccess = (healthControllerGetLivenessResponse200) & {
  headers: Headers;
};
;

export type healthControllerGetLivenessResponse = (healthControllerGetLivenessResponseSuccess)

export const getHealthControllerGetLivenessUrl = () => {




  return `http://localhost:4000/health/liveness`
}

export const healthControllerGetLiveness = async ( options?: RequestInit): Promise<healthControllerGetLivenessResponse> => {

  const res = await fetch(getHealthControllerGetLivenessUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthControllerGetLivenessResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as healthControllerGetLivenessResponse
}





export const getHealthControllerGetLivenessMutationKey = () => ['healthControllerGetLiveness'] as const;

export const getHealthControllerGetLivenessMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof healthControllerGetLiveness>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof healthControllerGetLiveness>>, TError,void, TContext> => {

const mutationKey = getHealthControllerGetLivenessMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof healthControllerGetLiveness>>, void> = () => {


          return  healthControllerGetLiveness(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type HealthControllerGetLivenessMutationResult = NonNullable<Awaited<ReturnType<typeof healthControllerGetLiveness>>>

    export type HealthControllerGetLivenessMutationError = unknown


    export const useHealthControllerGetLiveness = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof healthControllerGetLiveness>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof healthControllerGetLiveness>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getHealthControllerGetLivenessMutationOptions(options), queryClient);
    }

export type healthControllerGetReadinessResponse200 = {
  data: void
  status: 200
}

export type healthControllerGetReadinessResponseSuccess = (healthControllerGetReadinessResponse200) & {
  headers: Headers;
};
;

export type healthControllerGetReadinessResponse = (healthControllerGetReadinessResponseSuccess)

export const getHealthControllerGetReadinessUrl = () => {




  return `http://localhost:4000/health/readiness`
}

export const healthControllerGetReadiness = async ( options?: RequestInit): Promise<healthControllerGetReadinessResponse> => {

  const res = await fetch(getHealthControllerGetReadinessUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthControllerGetReadinessResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as healthControllerGetReadinessResponse
}





export const getHealthControllerGetReadinessMutationKey = () => ['healthControllerGetReadiness'] as const;

export const getHealthControllerGetReadinessMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof healthControllerGetReadiness>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof healthControllerGetReadiness>>, TError,void, TContext> => {

const mutationKey = getHealthControllerGetReadinessMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof healthControllerGetReadiness>>, void> = () => {


          return  healthControllerGetReadiness(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type HealthControllerGetReadinessMutationResult = NonNullable<Awaited<ReturnType<typeof healthControllerGetReadiness>>>

    export type HealthControllerGetReadinessMutationError = unknown


    export const useHealthControllerGetReadiness = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof healthControllerGetReadiness>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof healthControllerGetReadiness>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getHealthControllerGetReadinessMutationOptions(options), queryClient);
    }

export type filesControllerPresignUploadResponse201 = {
  data: void
  status: 201
}

export type filesControllerPresignUploadResponseSuccess = (filesControllerPresignUploadResponse201) & {
  headers: Headers;
};
;

export type filesControllerPresignUploadResponse = (filesControllerPresignUploadResponseSuccess)

export const getFilesControllerPresignUploadUrl = (projectId: string,) => {




  return `http://localhost:4000/api/v1/projects/${projectId}/files/presign-upload`
}

export const filesControllerPresignUpload = async (projectId: string, options?: RequestInit): Promise<filesControllerPresignUploadResponse> => {

  const res = await fetch(getFilesControllerPresignUploadUrl(projectId),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filesControllerPresignUploadResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as filesControllerPresignUploadResponse
}





export const getFilesControllerPresignUploadQueryKey = (projectId: string,) => {
    return [
    'POST', `http://localhost:4000/api/v1/projects/${projectId}/files/presign-upload`
    ] as const;
    }


export const getFilesControllerPresignUploadQueryOptions = <TData = Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError = unknown>(projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFilesControllerPresignUploadQueryKey(projectId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof filesControllerPresignUpload>>> = ({ signal }) => filesControllerPresignUpload(projectId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FilesControllerPresignUploadQueryResult = NonNullable<Awaited<ReturnType<typeof filesControllerPresignUpload>>>
export type FilesControllerPresignUploadQueryError = unknown


export function useFilesControllerPresignUpload<TData = Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError = unknown>(
 projectId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerPresignUpload>>,
          TError,
          Awaited<ReturnType<typeof filesControllerPresignUpload>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesControllerPresignUpload<TData = Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError = unknown>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerPresignUpload>>,
          TError,
          Awaited<ReturnType<typeof filesControllerPresignUpload>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesControllerPresignUpload<TData = Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError = unknown>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFilesControllerPresignUpload<TData = Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError = unknown>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFilesControllerPresignUploadQueryOptions(projectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type filesControllerConfirmUploadResponse201 = {
  data: void
  status: 201
}

export type filesControllerConfirmUploadResponseSuccess = (filesControllerConfirmUploadResponse201) & {
  headers: Headers;
};
;

export type filesControllerConfirmUploadResponse = (filesControllerConfirmUploadResponseSuccess)

export const getFilesControllerConfirmUploadUrl = (projectId: string,
    fileId: string,) => {




  return `http://localhost:4000/api/v1/projects/${projectId}/files/${fileId}/confirm`
}

export const filesControllerConfirmUpload = async (projectId: string,
    fileId: string, options?: RequestInit): Promise<filesControllerConfirmUploadResponse> => {

  const res = await fetch(getFilesControllerConfirmUploadUrl(projectId,fileId),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filesControllerConfirmUploadResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as filesControllerConfirmUploadResponse
}





export const getFilesControllerConfirmUploadQueryKey = (projectId: string,
    fileId: string,) => {
    return [
    'POST', `http://localhost:4000/api/v1/projects/${projectId}/files/${fileId}/confirm`
    ] as const;
    }


export const getFilesControllerConfirmUploadQueryOptions = <TData = Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError = unknown>(projectId: string,
    fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFilesControllerConfirmUploadQueryKey(projectId,fileId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof filesControllerConfirmUpload>>> = ({ signal }) => filesControllerConfirmUpload(projectId,fileId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined && fileId !== null && fileId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FilesControllerConfirmUploadQueryResult = NonNullable<Awaited<ReturnType<typeof filesControllerConfirmUpload>>>
export type FilesControllerConfirmUploadQueryError = unknown


export function useFilesControllerConfirmUpload<TData = Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError = unknown>(
 projectId: string,
    fileId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerConfirmUpload>>,
          TError,
          Awaited<ReturnType<typeof filesControllerConfirmUpload>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesControllerConfirmUpload<TData = Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError = unknown>(
 projectId: string,
    fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerConfirmUpload>>,
          TError,
          Awaited<ReturnType<typeof filesControllerConfirmUpload>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesControllerConfirmUpload<TData = Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError = unknown>(
 projectId: string,
    fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFilesControllerConfirmUpload<TData = Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError = unknown>(
 projectId: string,
    fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFilesControllerConfirmUploadQueryOptions(projectId,fileId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type filesControllerPresignDownloadResponse200 = {
  data: void
  status: 200
}

export type filesControllerPresignDownloadResponseSuccess = (filesControllerPresignDownloadResponse200) & {
  headers: Headers;
};
;

export type filesControllerPresignDownloadResponse = (filesControllerPresignDownloadResponseSuccess)

export const getFilesControllerPresignDownloadUrl = (projectId: string,
    fileId: string,) => {




  return `http://localhost:4000/api/v1/projects/${projectId}/files/${fileId}/presign-download`
}

export const filesControllerPresignDownload = async (projectId: string,
    fileId: string, options?: RequestInit): Promise<filesControllerPresignDownloadResponse> => {

  const res = await fetch(getFilesControllerPresignDownloadUrl(projectId,fileId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filesControllerPresignDownloadResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as filesControllerPresignDownloadResponse
}





export const getFilesControllerPresignDownloadMutationKey = () => ['filesControllerPresignDownload'] as const;

export const getFilesControllerPresignDownloadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerPresignDownload>>, TError,FilesControllerPresignDownloadMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof filesControllerPresignDownload>>, TError,FilesControllerPresignDownloadMutationVariables, TContext> => {

const mutationKey = getFilesControllerPresignDownloadMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof filesControllerPresignDownload>>, FilesControllerPresignDownloadMutationVariables> = (props) => {
          const {projectId,fileId} = props ?? {};

          return  filesControllerPresignDownload(projectId,fileId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FilesControllerPresignDownloadMutationResult = NonNullable<Awaited<ReturnType<typeof filesControllerPresignDownload>>>

    export type FilesControllerPresignDownloadMutationError = unknown
    export type FilesControllerPresignDownloadMutationVariables = {projectId: string;fileId: string}

    export const useFilesControllerPresignDownload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerPresignDownload>>, TError,FilesControllerPresignDownloadMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof filesControllerPresignDownload>>,
        TError,
        FilesControllerPresignDownloadMutationVariables,
        TContext
      > => {
      return useMutation(getFilesControllerPresignDownloadMutationOptions(options), queryClient);
    }

export type filesControllerListFilesResponse200 = {
  data: void
  status: 200
}

export type filesControllerListFilesResponseSuccess = (filesControllerListFilesResponse200) & {
  headers: Headers;
};
;

export type filesControllerListFilesResponse = (filesControllerListFilesResponseSuccess)

export const getFilesControllerListFilesUrl = (projectId: string,) => {




  return `http://localhost:4000/api/v1/projects/${projectId}/files`
}

export const filesControllerListFiles = async (projectId: string, options?: RequestInit): Promise<filesControllerListFilesResponse> => {

  const res = await fetch(getFilesControllerListFilesUrl(projectId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filesControllerListFilesResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as filesControllerListFilesResponse
}





export const getFilesControllerListFilesMutationKey = () => ['filesControllerListFiles'] as const;

export const getFilesControllerListFilesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerListFiles>>, TError,FilesControllerListFilesMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof filesControllerListFiles>>, TError,FilesControllerListFilesMutationVariables, TContext> => {

const mutationKey = getFilesControllerListFilesMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof filesControllerListFiles>>, FilesControllerListFilesMutationVariables> = (props) => {
          const {projectId} = props ?? {};

          return  filesControllerListFiles(projectId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FilesControllerListFilesMutationResult = NonNullable<Awaited<ReturnType<typeof filesControllerListFiles>>>

    export type FilesControllerListFilesMutationError = unknown
    export type FilesControllerListFilesMutationVariables = {projectId: string}

    export const useFilesControllerListFiles = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerListFiles>>, TError,FilesControllerListFilesMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof filesControllerListFiles>>,
        TError,
        FilesControllerListFilesMutationVariables,
        TContext
      > => {
      return useMutation(getFilesControllerListFilesMutationOptions(options), queryClient);
    }

export type filesControllerGetFileResponse200 = {
  data: void
  status: 200
}

export type filesControllerGetFileResponseSuccess = (filesControllerGetFileResponse200) & {
  headers: Headers;
};
;

export type filesControllerGetFileResponse = (filesControllerGetFileResponseSuccess)

export const getFilesControllerGetFileUrl = (projectId: string,
    fileId: string,) => {




  return `http://localhost:4000/api/v1/projects/${projectId}/files/${fileId}`
}

export const filesControllerGetFile = async (projectId: string,
    fileId: string, options?: RequestInit): Promise<filesControllerGetFileResponse> => {

  const res = await fetch(getFilesControllerGetFileUrl(projectId,fileId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filesControllerGetFileResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as filesControllerGetFileResponse
}





export const getFilesControllerGetFileMutationKey = () => ['filesControllerGetFile'] as const;

export const getFilesControllerGetFileMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerGetFile>>, TError,FilesControllerGetFileMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof filesControllerGetFile>>, TError,FilesControllerGetFileMutationVariables, TContext> => {

const mutationKey = getFilesControllerGetFileMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof filesControllerGetFile>>, FilesControllerGetFileMutationVariables> = (props) => {
          const {projectId,fileId} = props ?? {};

          return  filesControllerGetFile(projectId,fileId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FilesControllerGetFileMutationResult = NonNullable<Awaited<ReturnType<typeof filesControllerGetFile>>>

    export type FilesControllerGetFileMutationError = unknown
    export type FilesControllerGetFileMutationVariables = {projectId: string;fileId: string}

    export const useFilesControllerGetFile = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerGetFile>>, TError,FilesControllerGetFileMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof filesControllerGetFile>>,
        TError,
        FilesControllerGetFileMutationVariables,
        TContext
      > => {
      return useMutation(getFilesControllerGetFileMutationOptions(options), queryClient);
    }

export type auditControllerVerifyLedgerResponse200 = {
  data: void
  status: 200
}

export type auditControllerVerifyLedgerResponseSuccess = (auditControllerVerifyLedgerResponse200) & {
  headers: Headers;
};
;

export type auditControllerVerifyLedgerResponse = (auditControllerVerifyLedgerResponseSuccess)

export const getAuditControllerVerifyLedgerUrl = () => {




  return `http://localhost:4000/api/v1/audit/verify`
}

export const auditControllerVerifyLedger = async ( options?: RequestInit): Promise<auditControllerVerifyLedgerResponse> => {

  const res = await fetch(getAuditControllerVerifyLedgerUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: auditControllerVerifyLedgerResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as auditControllerVerifyLedgerResponse
}





export const getAuditControllerVerifyLedgerMutationKey = () => ['auditControllerVerifyLedger'] as const;

export const getAuditControllerVerifyLedgerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof auditControllerVerifyLedger>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof auditControllerVerifyLedger>>, TError,void, TContext> => {

const mutationKey = getAuditControllerVerifyLedgerMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof auditControllerVerifyLedger>>, void> = () => {


          return  auditControllerVerifyLedger(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuditControllerVerifyLedgerMutationResult = NonNullable<Awaited<ReturnType<typeof auditControllerVerifyLedger>>>

    export type AuditControllerVerifyLedgerMutationError = unknown


    export const useAuditControllerVerifyLedger = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof auditControllerVerifyLedger>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof auditControllerVerifyLedger>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuditControllerVerifyLedgerMutationOptions(options), queryClient);
    }

export type auditControllerGetEventsResponse200 = {
  data: void
  status: 200
}

export type auditControllerGetEventsResponseSuccess = (auditControllerGetEventsResponse200) & {
  headers: Headers;
};
;

export type auditControllerGetEventsResponse = (auditControllerGetEventsResponseSuccess)

export const getAuditControllerGetEventsUrl = (params: AuditControllerGetEventsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:4000/api/v1/audit/events?${stringifiedParams}` : `http://localhost:4000/api/v1/audit/events`
}

export const auditControllerGetEvents = async (params: AuditControllerGetEventsParams, options?: RequestInit): Promise<auditControllerGetEventsResponse> => {

  const res = await fetch(getAuditControllerGetEventsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: auditControllerGetEventsResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as auditControllerGetEventsResponse
}





export const getAuditControllerGetEventsMutationKey = () => ['auditControllerGetEvents'] as const;

export const getAuditControllerGetEventsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof auditControllerGetEvents>>, TError,AuditControllerGetEventsMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof auditControllerGetEvents>>, TError,AuditControllerGetEventsMutationVariables, TContext> => {

const mutationKey = getAuditControllerGetEventsMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof auditControllerGetEvents>>, AuditControllerGetEventsMutationVariables> = (props) => {
          const {params} = props ?? {};

          return  auditControllerGetEvents(params,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuditControllerGetEventsMutationResult = NonNullable<Awaited<ReturnType<typeof auditControllerGetEvents>>>

    export type AuditControllerGetEventsMutationError = unknown
    export type AuditControllerGetEventsMutationVariables = {params: AuditControllerGetEventsParams}

    export const useAuditControllerGetEvents = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof auditControllerGetEvents>>, TError,AuditControllerGetEventsMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof auditControllerGetEvents>>,
        TError,
        AuditControllerGetEventsMutationVariables,
        TContext
      > => {
      return useMutation(getAuditControllerGetEventsMutationOptions(options), queryClient);
    }

export type exportControllerTriggerExportResponse201 = {
  data: void
  status: 201
}

export type exportControllerTriggerExportResponseSuccess = (exportControllerTriggerExportResponse201) & {
  headers: Headers;
};
;

export type exportControllerTriggerExportResponse = (exportControllerTriggerExportResponseSuccess)

export const getExportControllerTriggerExportUrl = (projectId: string,
    analysisId: string,) => {




  return `http://localhost:4000/api/v1/projects/${projectId}/analyses/${analysisId}/export`
}

export const exportControllerTriggerExport = async (projectId: string,
    analysisId: string, options?: RequestInit): Promise<exportControllerTriggerExportResponse> => {

  const res = await fetch(getExportControllerTriggerExportUrl(projectId,analysisId),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: exportControllerTriggerExportResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as exportControllerTriggerExportResponse
}





export const getExportControllerTriggerExportQueryKey = (projectId: string,
    analysisId: string,) => {
    return [
    'POST', `http://localhost:4000/api/v1/projects/${projectId}/analyses/${analysisId}/export`
    ] as const;
    }


export const getExportControllerTriggerExportQueryOptions = <TData = Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError = unknown>(projectId: string,
    analysisId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExportControllerTriggerExportQueryKey(projectId,analysisId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof exportControllerTriggerExport>>> = ({ signal }) => exportControllerTriggerExport(projectId,analysisId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined && analysisId !== null && analysisId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExportControllerTriggerExportQueryResult = NonNullable<Awaited<ReturnType<typeof exportControllerTriggerExport>>>
export type ExportControllerTriggerExportQueryError = unknown


export function useExportControllerTriggerExport<TData = Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError = unknown>(
 projectId: string,
    analysisId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportControllerTriggerExport>>,
          TError,
          Awaited<ReturnType<typeof exportControllerTriggerExport>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportControllerTriggerExport<TData = Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError = unknown>(
 projectId: string,
    analysisId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportControllerTriggerExport>>,
          TError,
          Awaited<ReturnType<typeof exportControllerTriggerExport>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportControllerTriggerExport<TData = Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError = unknown>(
 projectId: string,
    analysisId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useExportControllerTriggerExport<TData = Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError = unknown>(
 projectId: string,
    analysisId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportControllerTriggerExport>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExportControllerTriggerExportQueryOptions(projectId,analysisId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type exportControllerGetReportsResponse200 = {
  data: void
  status: 200
}

export type exportControllerGetReportsResponseSuccess = (exportControllerGetReportsResponse200) & {
  headers: Headers;
};
;

export type exportControllerGetReportsResponse = (exportControllerGetReportsResponseSuccess)

export const getExportControllerGetReportsUrl = (projectId: string,
    analysisId: string,) => {




  return `http://localhost:4000/api/v1/projects/${projectId}/analyses/${analysisId}/reports`
}

export const exportControllerGetReports = async (projectId: string,
    analysisId: string, options?: RequestInit): Promise<exportControllerGetReportsResponse> => {

  const res = await fetch(getExportControllerGetReportsUrl(projectId,analysisId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: exportControllerGetReportsResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as exportControllerGetReportsResponse
}





export const getExportControllerGetReportsMutationKey = () => ['exportControllerGetReports'] as const;

export const getExportControllerGetReportsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof exportControllerGetReports>>, TError,ExportControllerGetReportsMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof exportControllerGetReports>>, TError,ExportControllerGetReportsMutationVariables, TContext> => {

const mutationKey = getExportControllerGetReportsMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof exportControllerGetReports>>, ExportControllerGetReportsMutationVariables> = (props) => {
          const {projectId,analysisId} = props ?? {};

          return  exportControllerGetReports(projectId,analysisId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ExportControllerGetReportsMutationResult = NonNullable<Awaited<ReturnType<typeof exportControllerGetReports>>>

    export type ExportControllerGetReportsMutationError = unknown
    export type ExportControllerGetReportsMutationVariables = {projectId: string;analysisId: string}

    export const useExportControllerGetReports = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof exportControllerGetReports>>, TError,ExportControllerGetReportsMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof exportControllerGetReports>>,
        TError,
        ExportControllerGetReportsMutationVariables,
        TContext
      > => {
      return useMutation(getExportControllerGetReportsMutationOptions(options), queryClient);
    }

export type exportControllerGetDownloadResponse200 = {
  data: void
  status: 200
}

export type exportControllerGetDownloadResponseSuccess = (exportControllerGetDownloadResponse200) & {
  headers: Headers;
};
;

export type exportControllerGetDownloadResponse = (exportControllerGetDownloadResponseSuccess)

export const getExportControllerGetDownloadUrl = (reportId: string,) => {




  return `http://localhost:4000/api/v1/reports/${reportId}/download`
}

export const exportControllerGetDownload = async (reportId: string, options?: RequestInit): Promise<exportControllerGetDownloadResponse> => {

  const res = await fetch(getExportControllerGetDownloadUrl(reportId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: exportControllerGetDownloadResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as exportControllerGetDownloadResponse
}





export const getExportControllerGetDownloadMutationKey = () => ['exportControllerGetDownload'] as const;

export const getExportControllerGetDownloadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof exportControllerGetDownload>>, TError,ExportControllerGetDownloadMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof exportControllerGetDownload>>, TError,ExportControllerGetDownloadMutationVariables, TContext> => {

const mutationKey = getExportControllerGetDownloadMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof exportControllerGetDownload>>, ExportControllerGetDownloadMutationVariables> = (props) => {
          const {reportId} = props ?? {};

          return  exportControllerGetDownload(reportId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ExportControllerGetDownloadMutationResult = NonNullable<Awaited<ReturnType<typeof exportControllerGetDownload>>>

    export type ExportControllerGetDownloadMutationError = unknown
    export type ExportControllerGetDownloadMutationVariables = {reportId: string}

    export const useExportControllerGetDownload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof exportControllerGetDownload>>, TError,ExportControllerGetDownloadMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof exportControllerGetDownload>>,
        TError,
        ExportControllerGetDownloadMutationVariables,
        TContext
      > => {
      return useMutation(getExportControllerGetDownloadMutationOptions(options), queryClient);
    }
