/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Preflight Core API
 * Enterprise multi-tenant preflight analysis and clean core auditing API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../../../production-custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type jobsControllerTriggerAnalysisResponse201 = {
  data: void
  status: 201
}

export type jobsControllerTriggerAnalysisResponseSuccess = (jobsControllerTriggerAnalysisResponse201) & {
  headers: Headers;
};
;

export type jobsControllerTriggerAnalysisResponse = (jobsControllerTriggerAnalysisResponseSuccess)

export const getJobsControllerTriggerAnalysisUrl = () => {




  return `/api/v1/jobs/analyze`
}

export const jobsControllerTriggerAnalysis = async ( options?: Parameters<typeof customInstance>[1]): Promise<jobsControllerTriggerAnalysisResponse> => {

  return customInstance<jobsControllerTriggerAnalysisResponse>(getJobsControllerTriggerAnalysisUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getJobsControllerTriggerAnalysisQueryKey = () => {
    return [
    'POST', `/api/v1/jobs/analyze`
    ] as const;
    }


export const getJobsControllerTriggerAnalysisQueryOptions = <TData = Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getJobsControllerTriggerAnalysisQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>> = ({ signal }) => jobsControllerTriggerAnalysis({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type JobsControllerTriggerAnalysisQueryResult = NonNullable<Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>>
export type JobsControllerTriggerAnalysisQueryError = unknown


export function useJobsControllerTriggerAnalysis<TData = Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>,
          TError,
          Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useJobsControllerTriggerAnalysis<TData = Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>,
          TError,
          Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useJobsControllerTriggerAnalysis<TData = Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useJobsControllerTriggerAnalysis<TData = Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jobsControllerTriggerAnalysis>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getJobsControllerTriggerAnalysisQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type jobsControllerGetAnalysisResponse200 = {
  data: void
  status: 200
}

export type jobsControllerGetAnalysisResponseSuccess = (jobsControllerGetAnalysisResponse200) & {
  headers: Headers;
};
;

export type jobsControllerGetAnalysisResponse = (jobsControllerGetAnalysisResponseSuccess)

export const getJobsControllerGetAnalysisUrl = (id: string,) => {




  return `/api/v1/jobs/${id}`
}

export const jobsControllerGetAnalysis = async (id: string, options?: Parameters<typeof customInstance>[1]): Promise<jobsControllerGetAnalysisResponse> => {

  return customInstance<jobsControllerGetAnalysisResponse>(getJobsControllerGetAnalysisUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getJobsControllerGetAnalysisMutationKey = () => ['jobsControllerGetAnalysis'] as const;

export const getJobsControllerGetAnalysisMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof jobsControllerGetAnalysis>>, TError,JobsControllerGetAnalysisMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof jobsControllerGetAnalysis>>, TError,JobsControllerGetAnalysisMutationVariables, TContext> => {

const mutationKey = getJobsControllerGetAnalysisMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof jobsControllerGetAnalysis>>, JobsControllerGetAnalysisMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  jobsControllerGetAnalysis(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type JobsControllerGetAnalysisMutationResult = NonNullable<Awaited<ReturnType<typeof jobsControllerGetAnalysis>>>

    export type JobsControllerGetAnalysisMutationError = unknown
    export type JobsControllerGetAnalysisMutationVariables = {id: string}

    export const useJobsControllerGetAnalysis = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof jobsControllerGetAnalysis>>, TError,JobsControllerGetAnalysisMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof jobsControllerGetAnalysis>>,
        TError,
        JobsControllerGetAnalysisMutationVariables,
        TContext
      > => {
      return useMutation(getJobsControllerGetAnalysisMutationOptions(options), queryClient);
    }
