/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ERP Preflight Core API
 * Enterprise multi-tenant preflight analysis and clean core auditing API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../../../../explorer_m2_orval_1/production-custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type filesControllerPresignUploadResponse201 = {
  data: void
  status: 201
}

export type filesControllerPresignUploadResponseSuccess = (filesControllerPresignUploadResponse201) & {
  headers: Headers;
};
;

export type filesControllerPresignUploadResponse = (filesControllerPresignUploadResponseSuccess)

export const getFilesControllerPresignUploadUrl = (projectId: string,) => {




  return `/api/v1/projects/${projectId}/files/presign-upload`
}

export const filesControllerPresignUpload = async (projectId: string, options?: Parameters<typeof customInstance>[1]): Promise<filesControllerPresignUploadResponse> => {

  return customInstance<filesControllerPresignUploadResponse>(getFilesControllerPresignUploadUrl(projectId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getFilesControllerPresignUploadMutationKey = () => ['filesControllerPresignUpload'] as const;

export const getFilesControllerPresignUploadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError,FilesControllerPresignUploadMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError,FilesControllerPresignUploadMutationVariables, TContext> => {

const mutationKey = getFilesControllerPresignUploadMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof filesControllerPresignUpload>>, FilesControllerPresignUploadMutationVariables> = (props) => {
          const {projectId} = props ?? {};

          return  filesControllerPresignUpload(projectId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FilesControllerPresignUploadMutationResult = NonNullable<Awaited<ReturnType<typeof filesControllerPresignUpload>>>

    export type FilesControllerPresignUploadMutationError = unknown
    export type FilesControllerPresignUploadMutationVariables = {projectId: string}

    export const useFilesControllerPresignUpload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerPresignUpload>>, TError,FilesControllerPresignUploadMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof filesControllerPresignUpload>>,
        TError,
        FilesControllerPresignUploadMutationVariables,
        TContext
      > => {
      return useMutation(getFilesControllerPresignUploadMutationOptions(options), queryClient);
    }
    export type filesControllerConfirmUploadResponse201 = {
  data: void
  status: 201
}

export type filesControllerConfirmUploadResponseSuccess = (filesControllerConfirmUploadResponse201) & {
  headers: Headers;
};
;

export type filesControllerConfirmUploadResponse = (filesControllerConfirmUploadResponseSuccess)

export const getFilesControllerConfirmUploadUrl = (projectId: string,
    fileId: string,) => {




  return `/api/v1/projects/${projectId}/files/${fileId}/confirm`
}

export const filesControllerConfirmUpload = async (projectId: string,
    fileId: string, options?: Parameters<typeof customInstance>[1]): Promise<filesControllerConfirmUploadResponse> => {

  return customInstance<filesControllerConfirmUploadResponse>(getFilesControllerConfirmUploadUrl(projectId,fileId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getFilesControllerConfirmUploadMutationKey = () => ['filesControllerConfirmUpload'] as const;

export const getFilesControllerConfirmUploadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError,FilesControllerConfirmUploadMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError,FilesControllerConfirmUploadMutationVariables, TContext> => {

const mutationKey = getFilesControllerConfirmUploadMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof filesControllerConfirmUpload>>, FilesControllerConfirmUploadMutationVariables> = (props) => {
          const {projectId,fileId} = props ?? {};

          return  filesControllerConfirmUpload(projectId,fileId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FilesControllerConfirmUploadMutationResult = NonNullable<Awaited<ReturnType<typeof filesControllerConfirmUpload>>>

    export type FilesControllerConfirmUploadMutationError = unknown
    export type FilesControllerConfirmUploadMutationVariables = {projectId: string;fileId: string}

    export const useFilesControllerConfirmUpload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesControllerConfirmUpload>>, TError,FilesControllerConfirmUploadMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof filesControllerConfirmUpload>>,
        TError,
        FilesControllerConfirmUploadMutationVariables,
        TContext
      > => {
      return useMutation(getFilesControllerConfirmUploadMutationOptions(options), queryClient);
    }
    export type filesControllerPresignDownloadResponse200 = {
  data: void
  status: 200
}

export type filesControllerPresignDownloadResponseSuccess = (filesControllerPresignDownloadResponse200) & {
  headers: Headers;
};
;

export type filesControllerPresignDownloadResponse = (filesControllerPresignDownloadResponseSuccess)

export const getFilesControllerPresignDownloadUrl = (projectId: string,
    fileId: string,) => {




  return `/api/v1/projects/${projectId}/files/${fileId}/presign-download`
}

export const filesControllerPresignDownload = async (projectId: string,
    fileId: string, options?: Parameters<typeof customInstance>[1]): Promise<filesControllerPresignDownloadResponse> => {

  return customInstance<filesControllerPresignDownloadResponse>(getFilesControllerPresignDownloadUrl(projectId,fileId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getFilesControllerPresignDownloadQueryKey = (projectId: string,
    fileId: string,) => {
    return [
    `/api/v1/projects/${projectId}/files/${fileId}/presign-download`
    ] as const;
    }


export const getFilesControllerPresignDownloadQueryOptions = <TData = Awaited<ReturnType<typeof filesControllerPresignDownload>>, TError = unknown>(projectId: string,
    fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerPresignDownload>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFilesControllerPresignDownloadQueryKey(projectId,fileId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof filesControllerPresignDownload>>> = ({ signal }) => filesControllerPresignDownload(projectId,fileId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined && fileId !== null && fileId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof filesControllerPresignDownload>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FilesControllerPresignDownloadQueryResult = NonNullable<Awaited<ReturnType<typeof filesControllerPresignDownload>>>
export type FilesControllerPresignDownloadQueryError = unknown


export function useFilesControllerPresignDownload<TData = Awaited<ReturnType<typeof filesControllerPresignDownload>>, TError = unknown>(
 projectId: string,
    fileId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerPresignDownload>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerPresignDownload>>,
          TError,
          Awaited<ReturnType<typeof filesControllerPresignDownload>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesControllerPresignDownload<TData = Awaited<ReturnType<typeof filesControllerPresignDownload>>, TError = unknown>(
 projectId: string,
    fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerPresignDownload>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerPresignDownload>>,
          TError,
          Awaited<ReturnType<typeof filesControllerPresignDownload>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesControllerPresignDownload<TData = Awaited<ReturnType<typeof filesControllerPresignDownload>>, TError = unknown>(
 projectId: string,
    fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerPresignDownload>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFilesControllerPresignDownload<TData = Awaited<ReturnType<typeof filesControllerPresignDownload>>, TError = unknown>(
 projectId: string,
    fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerPresignDownload>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFilesControllerPresignDownloadQueryOptions(projectId,fileId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type filesControllerListFilesResponse200 = {
  data: void
  status: 200
}

export type filesControllerListFilesResponseSuccess = (filesControllerListFilesResponse200) & {
  headers: Headers;
};
;

export type filesControllerListFilesResponse = (filesControllerListFilesResponseSuccess)

export const getFilesControllerListFilesUrl = (projectId: string,) => {




  return `/api/v1/projects/${projectId}/files`
}

export const filesControllerListFiles = async (projectId: string, options?: Parameters<typeof customInstance>[1]): Promise<filesControllerListFilesResponse> => {

  return customInstance<filesControllerListFilesResponse>(getFilesControllerListFilesUrl(projectId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getFilesControllerListFilesQueryKey = (projectId: string,) => {
    return [
    `/api/v1/projects/${projectId}/files`
    ] as const;
    }


export const getFilesControllerListFilesQueryOptions = <TData = Awaited<ReturnType<typeof filesControllerListFiles>>, TError = unknown>(projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerListFiles>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFilesControllerListFilesQueryKey(projectId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof filesControllerListFiles>>> = ({ signal }) => filesControllerListFiles(projectId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof filesControllerListFiles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FilesControllerListFilesQueryResult = NonNullable<Awaited<ReturnType<typeof filesControllerListFiles>>>
export type FilesControllerListFilesQueryError = unknown


export function useFilesControllerListFiles<TData = Awaited<ReturnType<typeof filesControllerListFiles>>, TError = unknown>(
 projectId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerListFiles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerListFiles>>,
          TError,
          Awaited<ReturnType<typeof filesControllerListFiles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesControllerListFiles<TData = Awaited<ReturnType<typeof filesControllerListFiles>>, TError = unknown>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerListFiles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerListFiles>>,
          TError,
          Awaited<ReturnType<typeof filesControllerListFiles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesControllerListFiles<TData = Awaited<ReturnType<typeof filesControllerListFiles>>, TError = unknown>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerListFiles>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFilesControllerListFiles<TData = Awaited<ReturnType<typeof filesControllerListFiles>>, TError = unknown>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerListFiles>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFilesControllerListFilesQueryOptions(projectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type filesControllerGetFileResponse200 = {
  data: void
  status: 200
}

export type filesControllerGetFileResponseSuccess = (filesControllerGetFileResponse200) & {
  headers: Headers;
};
;

export type filesControllerGetFileResponse = (filesControllerGetFileResponseSuccess)

export const getFilesControllerGetFileUrl = (projectId: string,
    fileId: string,) => {




  return `/api/v1/projects/${projectId}/files/${fileId}`
}

export const filesControllerGetFile = async (projectId: string,
    fileId: string, options?: Parameters<typeof customInstance>[1]): Promise<filesControllerGetFileResponse> => {

  return customInstance<filesControllerGetFileResponse>(getFilesControllerGetFileUrl(projectId,fileId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getFilesControllerGetFileQueryKey = (projectId: string,
    fileId: string,) => {
    return [
    `/api/v1/projects/${projectId}/files/${fileId}`
    ] as const;
    }


export const getFilesControllerGetFileQueryOptions = <TData = Awaited<ReturnType<typeof filesControllerGetFile>>, TError = unknown>(projectId: string,
    fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerGetFile>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFilesControllerGetFileQueryKey(projectId,fileId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof filesControllerGetFile>>> = ({ signal }) => filesControllerGetFile(projectId,fileId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined && fileId !== null && fileId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof filesControllerGetFile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FilesControllerGetFileQueryResult = NonNullable<Awaited<ReturnType<typeof filesControllerGetFile>>>
export type FilesControllerGetFileQueryError = unknown


export function useFilesControllerGetFile<TData = Awaited<ReturnType<typeof filesControllerGetFile>>, TError = unknown>(
 projectId: string,
    fileId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerGetFile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerGetFile>>,
          TError,
          Awaited<ReturnType<typeof filesControllerGetFile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesControllerGetFile<TData = Awaited<ReturnType<typeof filesControllerGetFile>>, TError = unknown>(
 projectId: string,
    fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerGetFile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerGetFile>>,
          TError,
          Awaited<ReturnType<typeof filesControllerGetFile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesControllerGetFile<TData = Awaited<ReturnType<typeof filesControllerGetFile>>, TError = unknown>(
 projectId: string,
    fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerGetFile>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFilesControllerGetFile<TData = Awaited<ReturnType<typeof filesControllerGetFile>>, TError = unknown>(
 projectId: string,
    fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesControllerGetFile>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFilesControllerGetFileQueryOptions(projectId,fileId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






